import 'package:flutkit_ademin/demo/app/invoice/invoice_models.dart';

final InvoiceModel mockInvoice = InvoiceModel(
  invoiceNo: "#INV-2025-07-001",
  dateTime: DateTime(2025, 7, 3, 10, 0), // Changed date to current year
  paymentStatus: "Paid", //  payment status
  totalAmount: 1520.75, //  total amount

  companyInfo: CompanyInfo(
    logoUrl: 'assets/images/logo_light.png', //  logo path
    companyName: 'FlutKit Home Corp.', //  company name
    legalRegistrationNo: 'ABC-123-XYZ', //  registration number
    email: 'info@flutkit.com', //  email
    website: 'www.flutkit.com', //  website
    contactNo: '+(55) 11 9876-5432', //  contact number (Brazilian format)
    address: 'Metro City, Indonesia', //  address
    zipCode: '01001-000', //  zip code (Brazilian CEP format)
  ),
  billingAddress: Address(
    name: "Eleanor Vance", //  name
    street: "123 Maple Street", //  street
    phone: "+(987) 654-3210", //  phone
    tax: "98-7654321", //  tax
  ),
  shippingAddress: Address(
    name: "Eleanor Vance", //  name
    street: "Unit 5, 45 Elm Avenue", //  street
    phone: "+(987) 654-3210", //  phone
  ),
  items: [
    ProductItem(
      title: "Premium Wireless Headphones", //  product
      description: "Noise-cancelling, over-ear headphones",
      rate: 299.99,
      quantity: 2,
    ),
    ProductItem(
      title: "Ergonomic Office Chair", //  product
      description: "Adjustable with lumbar support",
      rate: 450.00,
      quantity: 1,
    ),
    ProductItem(
      title: "4K Ultra HD Smart TV", //  product
      description: "55-inch LED display, built-in streaming",
      rate: 799.00,
      quantity: 1,
    ),
  ],
  estimatedTaxPercent: 8.0, //  tax percentage
  discountAmount: 75.00, //  discount amount
  shippingCharge: 25.00, //  shipping charge
  paymentDetails: PaymentDetails(
    method: "Visa", //  payment method
    cardHolder: "Eleanor Vance", //  card holder
    cardNumber: "xxxx xxxx xxxx 5678", //  card number
  ),
);

// invoice data mockup

final List<InvoiceData> mockInvoices = [
  InvoiceData(
    id: 'INV-001',
    customerName: 'Alice Johnson',
    avatarUrl: 'assets/images/avatar_2.jpg',
    email: 'alice.johnson@example.com',
    country: 'USA',
    date: DateTime(2025, 7, 1),
    amount: 1247.00,
    status: PaymentStatus.paid,
  ),
  InvoiceData(
    id: 'INV-002',
    customerName: 'Michael Lee',
    avatarUrl: 'assets/images/avatar_3.jpg',
    email: 'michael.lee@example.com',
    country: 'Canada',
    date: DateTime(2025, 6, 28),
    amount: 987.50,
    status: PaymentStatus.unpaid,
  ),
  InvoiceData(
    id: 'INV-003',
    customerName: 'Sarah Williams',
    avatarUrl: 'assets/images/avatar_4.jpg',
    email: 'sarah.williams@example.com',
    country: 'UK',
    date: DateTime(2025, 6, 20),
    amount: 430.75,
    status: PaymentStatus.refund,
  ),
  InvoiceData(
    id: 'INV-004',
    customerName: 'John Doe',
    avatarUrl: 'assets/images/avatar_5.jpg',
    email: 'john.doe@example.com',
    country: 'Germany',
    date: DateTime(2025, 6, 15),
    amount: 650.00,
    status: PaymentStatus.cancel,
  ),
  InvoiceData(
    id: 'INV-005',
    customerName: 'Emily Brown',
    avatarUrl: 'assets/images/avatar_6.jpg',
    email: 'emily.brown@example.com',
    country: 'Australia',
    date: DateTime(2025, 7, 2),
    amount: 210.00,
    status: PaymentStatus.paid,
  ),
  InvoiceData(
    id: 'INV-006',
    customerName: 'David Kim',
    avatarUrl: 'assets/images/avatar_7.jpg',
    email: 'david.kim@example.com',
    country: 'South Korea',
    date: DateTime(2025, 6, 30),
    amount: 1500.00,
    status: PaymentStatus.unpaid,
  ),
  InvoiceData(
    id: 'INV-007',
    customerName: 'Olivia Garcia',
    avatarUrl: 'assets/images/avatar_8.jpg',
    email: 'olivia.garcia@example.com',
    country: 'Spain',
    date: DateTime(2025, 6, 25),
    amount: 720.50,
    status: PaymentStatus.paid,
  ),
  InvoiceData(
    id: 'INV-008',
    customerName: 'Daniel Martinez',
    avatarUrl: 'assets/images/avatar_9.jpg',
    email: 'daniel.martinez@example.com',
    country: 'Mexico',
    date: DateTime(2025, 6, 18),
    amount: 300.00,
    status: PaymentStatus.refund,
  ),
  InvoiceData(
    id: 'INV-009',
    customerName: 'Sophia Rodriguez',
    avatarUrl: 'assets/images/avatar_10.jpg',
    email: 'sophia.rodriguez@example.com',
    country: 'Argentina',
    date: DateTime(2025, 6, 10),
    amount: 900.00,
    status: PaymentStatus.cancel,
  ),
  InvoiceData(
    id: 'INV-010',
    customerName: 'James White',
    avatarUrl: 'assets/images/avatar_1.jpg',
    email: 'james.white@example.com',
    country: 'USA',
    date: DateTime(2025, 7, 3),
    amount: 1100.00,
    status: PaymentStatus.paid,
  ),
  InvoiceData(
    id: 'INV-011',
    customerName: 'Isabella Taylor',
    avatarUrl: 'assets/images/avatar_2.jpg',
    email: 'isabella.taylor@example.com',
    country: 'Canada',
    date: DateTime(2025, 6, 29),
    amount: 550.00,
    status: PaymentStatus.unpaid,
  ),
  InvoiceData(
    id: 'INV-012',
    customerName: 'William Chen',
    avatarUrl: 'assets/images/avatar_3.jpg',
    email: 'william.chen@example.com',
    country: 'China',
    date: DateTime(2025, 6, 22),
    amount: 2300.00,
    status: PaymentStatus.paid,
  ),
  InvoiceData(
    id: 'INV-013',
    customerName: 'Mia Hall',
    avatarUrl: 'assets/images/avatar_4.jpg',
    email: 'mia.hall@example.com',
    country: 'UK',
    date: DateTime(2025, 6, 17),
    amount: 880.00,
    status: PaymentStatus.refund,
  ),
  InvoiceData(
    id: 'INV-014',
    customerName: 'Alexander King',
    avatarUrl: 'assets/images/avatar_5.jpg',
    email: 'alexander.king@example.com',
    country: 'Germany',
    date: DateTime(2025, 6, 12),
    amount: 190.00,
    status: PaymentStatus.cancel,
  ),
  InvoiceData(
    id: 'INV-015',
    customerName: 'Charlotte Wright',
    avatarUrl: 'assets/images/avatar_6.jpg',
    email: 'charlotte.wright@example.com',
    country: 'Australia',
    date: DateTime(2025, 7, 4),
    amount: 670.00,
    status: PaymentStatus.paid,
  ),
  InvoiceData(
    id: 'INV-016',
    customerName: 'Benjamin Scott',
    avatarUrl: 'assets/images/avatar_7.jpg',
    email: 'benjamin.scott@example.com',
    country: 'USA',
    date: DateTime(2025, 6, 27),
    amount: 420.00,
    status: PaymentStatus.unpaid,
  ),
  InvoiceData(
    id: 'INV-017',
    customerName: 'Amelia Green',
    avatarUrl: 'assets/images/avatar_8.jpg',
    email: 'amelia.green@example.com',
    country: 'Canada',
    date: DateTime(2025, 6, 21),
    amount: 1050.00,
    status: PaymentStatus.paid,
  ),
  InvoiceData(
    id: 'INV-018',
    customerName: 'Ethan Adams',
    avatarUrl: 'assets/images/avatar_9.jpg',
    email: 'ethan.adams@example.com',
    country: 'UK',
    date: DateTime(2025, 6, 14),
    amount: 75.00,
    status: PaymentStatus.refund,
  ),
  InvoiceData(
    id: 'INV-019',
    customerName: 'Harper Baker',
    avatarUrl: 'assets/images/avatar_10.jpg',
    email: 'harper.baker@example.com',
    country: 'Germany',
    date: DateTime(2025, 6, 8),
    amount: 2000.00,
    status: PaymentStatus.cancel,
  ),
  InvoiceData(
    id: 'INV-020',
    customerName: 'Noah Nelson',
    avatarUrl: 'assets/images/avatar_1.jpg',
    email: 'noah.nelson@example.com',
    country: 'France',
    date: DateTime(2025, 7, 5),
    amount: 320.00,
    status: PaymentStatus.paid,
  ),
  InvoiceData(
    id: 'INV-021',
    customerName: 'Liam Carter',
    avatarUrl: 'assets/images/avatar_2.jpg',
    email: 'liam.carter@example.com',
    country: 'Ireland',
    date: DateTime(2025, 7, 6),
    amount: 810.00,
    status: PaymentStatus.paid,
  ),
  InvoiceData(
    id: 'INV-022',
    customerName: 'Ava Parker',
    avatarUrl: 'assets/images/avatar_3.jpg',
    email: 'ava.parker@example.com',
    country: 'New Zealand',
    date: DateTime(2025, 7, 7),
    amount: 120.00,
    status: PaymentStatus.unpaid,
  ),
  InvoiceData(
    id: 'INV-023',
    customerName: 'Lucas Evans',
    avatarUrl: 'assets/images/avatar_4.jpg',
    email: 'lucas.evans@example.com',
    country: 'UK',
    date: DateTime(2025, 7, 8),
    amount: 1500.00,
    status: PaymentStatus.paid,
  ),
  InvoiceData(
    id: 'INV-024',
    customerName: 'Sophie Turner',
    avatarUrl: 'assets/images/avatar_5.jpg',
    email: 'sophie.turner@example.com',
    country: 'France',
    date: DateTime(2025, 7, 9),
    amount: 450.00,
    status: PaymentStatus.refund,
  ),
  InvoiceData(
    id: 'INV-025',
    customerName: 'Mason Hill',
    avatarUrl: 'assets/images/avatar_6.jpg',
    email: 'mason.hill@example.com',
    country: 'USA',
    date: DateTime(2025, 7, 10),
    amount: 990.00,
    status: PaymentStatus.cancel,
  ),
  InvoiceData(
    id: 'INV-026',
    customerName: 'Chloe Lewis',
    avatarUrl: 'assets/images/avatar_7.jpg',
    email: 'chloe.lewis@example.com',
    country: 'Canada',
    date: DateTime(2025, 7, 11),
    amount: 280.00,
    status: PaymentStatus.paid,
  ),
  InvoiceData(
    id: 'INV-027',
    customerName: 'Elijah Clark',
    avatarUrl: 'assets/images/avatar_8.jpg',
    email: 'elijah.clark@example.com',
    country: 'Australia',
    date: DateTime(2025, 7, 12),
    amount: 1800.00,
    status: PaymentStatus.unpaid,
  ),
  InvoiceData(
    id: 'INV-028',
    customerName: 'Grace Roberts',
    avatarUrl: 'assets/images/avatar_9.jpg',
    email: 'grace.roberts@example.com',
    country: 'Germany',
    date: DateTime(2025, 7, 13),
    amount: 600.00,
    status: PaymentStatus.paid,
  ),
  InvoiceData(
    id: 'INV-029',
    customerName: 'Logan Walker',
    avatarUrl: 'assets/images/avatar_10.jpg',
    email: 'logan.walker@example.com',
    country: 'Spain',
    date: DateTime(2025, 7, 14),
    amount: 350.00,
    status: PaymentStatus.refund,
  ),
  InvoiceData(
    id: 'INV-030',
    customerName: 'Aria Young',
    avatarUrl: 'assets/images/avatar_1.jpg',
    email: 'aria.young@example.com',
    country: 'Mexico',
    date: DateTime(2025, 7, 15),
    amount: 700.00,
    status: PaymentStatus.cancel,
  ),
  InvoiceData(
    id: 'INV-031',
    customerName: 'Jackson Harris',
    avatarUrl: 'assets/images/avatar_2.jpg',
    email: 'jackson.harris@example.com',
    country: 'Brazil',
    date: DateTime(2025, 7, 16),
    amount: 1120.00,
    status: PaymentStatus.paid,
  ),
  InvoiceData(
    id: 'INV-032',
    customerName: 'Ella King',
    avatarUrl: 'assets/images/avatar_3.jpg',
    email: 'ella.king@example.com',
    country: 'Argentina',
    date: DateTime(2025, 7, 17),
    amount: 50.00,
    status: PaymentStatus.unpaid,
  ),
  InvoiceData(
    id: 'INV-033',
    customerName: 'Sebastian Baker',
    avatarUrl: 'assets/images/avatar_4.jpg',
    email: 'sebastian.baker@example.com',
    country: 'USA',
    date: DateTime(2025, 7, 18),
    amount: 2500.00,
    status: PaymentStatus.paid,
  ),
  InvoiceData(
    id: 'INV-034',
    customerName: 'Zoe Carter',
    avatarUrl: 'assets/images/avatar_5.jpg',
    email: 'zoe.carter@example.com',
    country: 'Canada',
    date: DateTime(2025, 7, 19),
    amount: 130.00,
    status: PaymentStatus.refund,
  ),
  InvoiceData(
    id: 'INV-035',
    customerName: 'Owen Hill',
    avatarUrl: 'assets/images/avatar_6.jpg',
    email: 'owen.hill@example.com',
    country: 'UK',
    date: DateTime(2025, 7, 20),
    amount: 900.00,
    status: PaymentStatus.cancel,
  ),
  InvoiceData(
    id: 'INV-036',
    customerName: 'Lily Green',
    avatarUrl: 'assets/images/avatar_7.jpg',
    email: 'lily.green@example.com',
    country: 'Australia',
    date: DateTime(2025, 7, 21),
    amount: 400.00,
    status: PaymentStatus.paid,
  ),
  InvoiceData(
    id: 'INV-037',
    customerName: 'Gabriel White',
    avatarUrl: 'assets/images/avatar_8.jpg',
    email: 'gabriel.white@example.com',
    country: 'Germany',
    date: DateTime(2025, 7, 22),
    amount: 1600.00,
    status: PaymentStatus.unpaid,
  ),
  InvoiceData(
    id: 'INV-038',
    customerName: 'Layla Adams',
    avatarUrl: 'assets/images/avatar_9.jpg',
    email: 'layla.adams@example.com',
    country: 'France',
    date: DateTime(2025, 7, 23),
    amount: 780.00,
    status: PaymentStatus.paid,
  ),
  InvoiceData(
    id: 'INV-039',
    customerName: 'Samuel Hall',
    avatarUrl: 'assets/images/avatar_10.jpg',
    email: 'samuel.hall@example.com',
    country: 'Italy',
    date: DateTime(2025, 7, 24),
    amount: 220.00,
    status: PaymentStatus.refund,
  ),
  InvoiceData(
    id: 'INV-040',
    customerName: 'Victoria Lewis',
    avatarUrl: 'assets/images/avatar_1.jpg',
    email: 'victoria.lewis@example.com',
    country: 'USA',
    date: DateTime(2025, 7, 25),
    amount: 550.00,
    status: PaymentStatus.cancel,
  ),
];
