import 'package:flutter_ademin/demo/page/gallery/gallery_models.dart';

final List<GalleryItem> galleryItems = [
  GalleryItem(
    imageUrl: 'assets/images/bg_1.jpg',
    author: 'Ron Omar',
    likes: 2200,
    comments: 1300,
    category: 'Nature',
  ),
  GalleryItem(
    imageUrl: 'assets/images/bg_2.jpg',
    author: 'Henry Bailey',
    likes: 1950,
    comments: 1100,
    category: 'Technology',
  ),
  GalleryItem(
    imageUrl: 'assets/images/bg_3.jpg',
    author: 'Jason McQuaid',
    likes: 825,
    comments: 401,
    category: 'People',
  ),
  GalleryItem(
    imageUrl: 'assets/images/bg_4.jpg',
    author: 'Ruby Griffin',
    likes: 1500,
    comments: 250,
    category: 'Urban',
  ),
  GalleryItem(
    imageUrl: 'assets/images/bg_5.jpg',
    author: 'Dylan Morse',
    likes: 1020,
    comments: 315,
    category: 'Nature',
  ),
  GalleryItem(
    imageUrl: 'assets/images/bg_6.jpg',
    author: 'Eva Langston',
    likes: 980,
    comments: 221,
    category: 'People',
  ),
  GalleryItem(
    imageUrl: 'assets/images/bg_7.jpg',
    author: 'Liam Patel',
    likes: 870,
    comments: 290,
    category: 'Technology',
  ),
  GalleryItem(
    imageUrl: 'assets/images/bg_8.jpg',
    author: 'Sophia Hwang',
    likes: 1340,
    comments: 445,
    category: 'Urban',
  ),
  GalleryItem(
    imageUrl: 'assets/images/bg_9.jpg',
    author: 'Mohammed Aziz',
    likes: 920,
    comments: 180,
    category: 'Nature',
  ),
  GalleryItem(
    imageUrl: 'assets/images/bg_10.jpg',
    author: 'Chloe Raines',
    likes: 1100,
    comments: 310,
    category: 'People',
  ),
  GalleryItem(
    imageUrl: 'assets/images/bg_11.jpg',
    author: 'Jasper Lee',
    likes: 750,
    comments: 140,
    category: 'Technology',
  ),
  GalleryItem(
    imageUrl: 'assets/images/bg_12.jpg',
    author: 'Nina Schmidt',
    likes: 1650,
    comments: 410,
    category: 'Urban',
  ),
  GalleryItem(
    imageUrl: 'assets/images/bg_13.jpg',
    author: 'Avery Cole',
    likes: 1430,
    comments: 360,
    category: 'Nature',
  ),
  GalleryItem(
    imageUrl: 'assets/images/bg_14.jpg',
    author: 'Noah Kim',
    likes: 910,
    comments: 270,
    category: 'Technology',
  ),
  GalleryItem(
    imageUrl: 'assets/images/bg_15.jpg',
    author: 'Lily Zhang',
    likes: 1320,
    comments: 420,
    category: 'People',
  ),
  GalleryItem(
    imageUrl: 'assets/images/bg_16.jpg',
    author: 'Ethan Roy',
    likes: 990,
    comments: 310,
    category: 'Urban',
  ),
  GalleryItem(
    imageUrl: 'assets/images/bg_17.jpg',
    author: 'Isabella Singh',
    likes: 1280,
    comments: 330,
    category: 'Nature',
  ),
  GalleryItem(
    imageUrl: 'assets/images/bg_18.jpg',
    author: 'Mason Rivera',
    likes: 870,
    comments: 190,
    category: 'Technology',
  ),
  GalleryItem(
    imageUrl: 'assets/images/bg_19.jpg',
    author: 'Mila Hassan',
    likes: 1160,
    comments: 290,
    category: 'People',
  ),
  GalleryItem(
    imageUrl: 'assets/images/bg_20.jpg',
    author: 'Logan Chen',
    likes: 1400,
    comments: 370,
    category: 'Urban',
  ),
  GalleryItem(
    imageUrl: 'assets/images/bg_2.jpg',
    author: 'Henry Bailey',
    likes: 1950,
    comments: 1100,
    category: 'Nature',
  ),
  GalleryItem(
    imageUrl: 'assets/images/bg_3.jpg',
    author: 'Jason McQuaid',
    likes: 825,
    comments: 401,
    category: 'Nature',
  ),
  GalleryItem(
    imageUrl: 'assets/images/bg_4.jpg',
    author: 'Ruby Griffin',
    likes: 1500,
    comments: 250,
    category: 'Nature',
  ),
  GalleryItem(
    imageUrl: 'assets/images/bg_17.jpg',
    author: 'Isabella Singh',
    likes: 1280,
    comments: 330,
    category: 'Nature',
  ),
  GalleryItem(
    imageUrl: 'assets/images/bg_18.jpg',
    author: 'Mason Rivera',
    likes: 870,
    comments: 190,
    category: 'Nature',
  ),
  GalleryItem(
    imageUrl: 'assets/images/bg_19.jpg',
    author: 'Mila Hassan',
    likes: 1160,
    comments: 290,
    category: 'Nature',
  ),
  GalleryItem(
    imageUrl: 'assets/images/bg_20.jpg',
    author: 'Logan Chen',
    likes: 1400,
    comments: 370,
    category: 'Nature',
  ),

  //
  GalleryItem(
    imageUrl: 'assets/images/bg_1.jpg',
    author: 'Ron Omar',
    likes: 2200,
    comments: 1300,
    category: 'Technology',
  ),
  GalleryItem(
    imageUrl: 'assets/images/bg_2.jpg',
    author: 'Henry Bailey',
    likes: 1950,
    comments: 1100,
    category: 'Technology',
  ),
  GalleryItem(
    imageUrl: 'assets/images/bg_3.jpg',
    author: 'Jason McQuaid',
    likes: 825,
    comments: 401,
    category: 'Technology',
  ),
  GalleryItem(
    imageUrl: 'assets/images/bg_4.jpg',
    author: 'Ruby Griffin',
    likes: 1500,
    comments: 250,
    category: 'Technology',
  ),
  GalleryItem(
    imageUrl: 'assets/images/bg_5.jpg',
    author: 'Dylan Morse',
    likes: 1020,
    comments: 315,
    category: 'Technology',
  ),
  GalleryItem(
    imageUrl: 'assets/images/bg_6.jpg',
    author: 'Eva Langston',
    likes: 980,
    comments: 221,
    category: 'Technology',
  ),
  GalleryItem(
    imageUrl: 'assets/images/bg_7.jpg',
    author: 'Liam Patel',
    likes: 870,
    comments: 290,
    category: 'Technology',
  ),

  GalleryItem(
    imageUrl: 'assets/images/bg_20.jpg',
    author: 'Logan Chen',
    likes: 1400,
    comments: 370,
    category: 'People',
  ),
  GalleryItem(
    imageUrl: 'assets/images/bg_2.jpg',
    author: 'Henry Bailey',
    likes: 1950,
    comments: 1100,
    category: 'People',
  ),
  GalleryItem(
    imageUrl: 'assets/images/bg_3.jpg',
    author: 'Jason McQuaid',
    likes: 825,
    comments: 401,
    category: 'People',
  ),
  GalleryItem(
    imageUrl: 'assets/images/bg_4.jpg',
    author: 'Ruby Griffin',
    likes: 1500,
    comments: 250,
    category: 'People',
  ),
  GalleryItem(
    imageUrl: 'assets/images/bg_17.jpg',
    author: 'Isabella Singh',
    likes: 1280,
    comments: 330,
    category: 'People',
  ),
  GalleryItem(
    imageUrl: 'assets/images/bg_18.jpg',
    author: 'Mason Rivera',
    likes: 870,
    comments: 190,
    category: 'People',
  ),
  GalleryItem(
    imageUrl: 'assets/images/bg_19.jpg',
    author: 'Mila Hassan',
    likes: 1160,
    comments: 290,
    category: 'Urban',
  ),
  GalleryItem(
    imageUrl: 'assets/images/bg_20.jpg',
    author: 'Logan Chen',
    likes: 1400,
    comments: 370,
    category: 'Urban',
  ),

  GalleryItem(
    imageUrl: 'assets/images/bg_5.jpg',
    author: 'Dylan Morse',
    likes: 1020,
    comments: 315,
    category: 'Urban',
  ),
  GalleryItem(
    imageUrl: 'assets/images/bg_6.jpg',
    author: 'Eva Langston',
    likes: 980,
    comments: 221,
    category: 'Urban',
  ),
];
