// user mock up data

import 'package:flutter_ademin/demo/app/user_management/user_management_models.dart';

final List<UserModel> mockUsers = [
  UserModel(
    avatarUrl: 'assets/images/avatar_1.jpg',
    fullName: 'Daniel Robertson',
    email: 'daniel.robertson@saasapp.com',
    username: 'danielr',
    status: 'active',
    role: 'admin',
    joinedDate: DateTime(2023, 1, 12),
    lastActive: DateTime(2026, 2, 3),
    plan: 'enterprise',
  ),
  UserModel(
    avatarUrl: 'assets/images/avatar_2.jpg',
    fullName: 'Sarah Williams',
    email: 'sarah.williams@saasapp.com',
    username: 'sarahw',
    status: 'active',
    role: 'manager',
    joinedDate: DateTime(2023, 2, 5),
    lastActive: DateTime(2026, 2, 2),
    plan: 'pro',
  ),
  UserModel(
    avatarUrl: 'assets/images/avatar_3.jpg',
    fullName: 'Michael Chen',
    email: 'michael.chen@saasapp.com',
    username: 'mchen',
    status: 'inactive',
    role: 'member',
    joinedDate: DateTime(2023, 3, 10),
    lastActive: DateTime(2025, 11, 12),
    plan: 'free',
  ),
  UserModel(
    avatarUrl: 'assets/images/avatar_4.jpg',
    fullName: 'Alicia Gomez',
    email: 'alicia.gomez@saasapp.com',
    username: 'agomez',
    status: 'active',
    role: 'support',
    joinedDate: DateTime(2023, 3, 18),
    lastActive: DateTime(2026, 2, 1),
    plan: 'starter',
  ),
  UserModel(
    avatarUrl: 'assets/images/avatar_5.jpg',
    fullName: 'Thomas Becker',
    email: 'thomas.becker@saasapp.com',
    username: 'tbecker',
    status: 'suspended',
    role: 'member',
    joinedDate: DateTime(2023, 4, 2),
    lastActive: DateTime(2025, 12, 20),
    plan: 'pro',
  ),
  UserModel(
    avatarUrl: 'assets/images/avatar_6.jpg',
    fullName: 'Nina Petrova',
    email: 'nina.petrova@saasapp.com',
    username: 'npetrova',
    status: 'active',
    role: 'manager',
    joinedDate: DateTime(2023, 4, 15),
    lastActive: DateTime(2026, 2, 3),
    plan: 'enterprise',
  ),
  UserModel(
    avatarUrl: 'assets/images/avatar_7.jpg',
    fullName: 'James O’Connor',
    email: 'james.oconnor@saasapp.com',
    username: 'joconnor',
    status: 'active',
    role: 'member',
    joinedDate: DateTime(2023, 5, 1),
    lastActive: DateTime(2026, 1, 30),
    plan: 'starter',
  ),
  UserModel(
    avatarUrl: 'assets/images/avatar_8.jpg',
    fullName: 'Linda Park',
    email: 'linda.park@saasapp.com',
    username: 'lpark',
    status: 'banned',
    role: 'member',
    joinedDate: DateTime(2023, 5, 12),
    lastActive: DateTime(2025, 9, 5),
    plan: 'free',
  ),
  UserModel(
    avatarUrl: 'assets/images/avatar_9.jpg',
    fullName: 'Victor Ivanov',
    email: 'victor.ivanov@saasapp.com',
    username: 'vivanov',
    status: 'active',
    role: 'support',
    joinedDate: DateTime(2023, 6, 3),
    lastActive: DateTime(2026, 2, 4),
    plan: 'pro',
  ),
  UserModel(
    avatarUrl: 'assets/images/avatar_10.jpg',
    fullName: 'Emily Carter',
    email: 'emily.carter@saasapp.com',
    username: 'ecarter',
    status: 'inactive',
    role: 'member',
    joinedDate: DateTime(2023, 6, 20),
    lastActive: DateTime(2025, 10, 12),
    plan: 'free',
  ),

  UserModel(
    avatarUrl: 'assets/images/avatar_11.jpg',
    fullName: 'Robert Kim',
    email: 'robert.kim@saasapp.com',
    username: 'rkim',
    status: 'active',
    role: 'manager',
    joinedDate: DateTime(2023, 7, 2),
    lastActive: DateTime(2026, 2, 3),
    plan: 'enterprise',
  ),
  UserModel(
    avatarUrl: 'assets/images/avatar_1.jpg',
    fullName: 'Hannah Schmidt',
    email: 'hannah.schmidt@saasapp.com',
    username: 'hschmidt',
    status: 'active',
    role: 'member',
    joinedDate: DateTime(2023, 7, 18),
    lastActive: DateTime(2026, 1, 29),
    plan: 'pro',
  ),
  UserModel(
    avatarUrl: 'assets/images/avatar_2.jpg',
    fullName: 'Ahmed Hassan',
    email: 'ahmed.hassan@saasapp.com',
    username: 'ahassan',
    status: 'suspended',
    role: 'support',
    joinedDate: DateTime(2023, 8, 1),
    lastActive: DateTime(2025, 12, 2),
    plan: 'starter',
  ),
  UserModel(
    avatarUrl: 'assets/images/avatar_3.jpg',
    fullName: 'Julia Novak',
    email: 'julia.novak@saasapp.com',
    username: 'jnovak',
    status: 'active',
    role: 'member',
    joinedDate: DateTime(2023, 8, 9),
    lastActive: DateTime(2026, 2, 1),
    plan: 'pro',
  ),
  UserModel(
    avatarUrl: 'assets/images/avatar_4.jpg',
    fullName: 'Diego Morales',
    email: 'diego.morales@saasapp.com',
    username: 'dmorales',
    status: 'active',
    role: 'support',
    joinedDate: DateTime(2023, 9, 3),
    lastActive: DateTime(2026, 2, 4),
    plan: 'enterprise',
  ),
  UserModel(
    avatarUrl: 'assets/images/avatar_5.jpg',
    fullName: 'Sophia Laurent',
    email: 'sophia.laurent@saasapp.com',
    username: 'slaurent',
    status: 'banned',
    role: 'member',
    joinedDate: DateTime(2023, 9, 15),
    lastActive: DateTime(2025, 8, 19),
    plan: 'free',
  ),
  UserModel(
    avatarUrl: 'assets/images/avatar_6.jpg',
    fullName: 'Kevin Brown',
    email: 'kevin.brown@saasapp.com',
    username: 'kbrown',
    status: 'active',
    role: 'manager',
    joinedDate: DateTime(2023, 10, 1),
    lastActive: DateTime(2026, 2, 3),
    plan: 'pro',
  ),
  UserModel(
    avatarUrl: 'assets/images/avatar_7.jpg',
    fullName: 'Natalie Wong',
    email: 'natalie.wong@saasapp.com',
    username: 'nwong',
    status: 'inactive',
    role: 'member',
    joinedDate: DateTime(2023, 10, 10),
    lastActive: DateTime(2025, 11, 1),
    plan: 'free',
  ),
  UserModel(
    avatarUrl: 'assets/images/avatar_8.jpg',
    fullName: 'Lucas Ferreira',
    email: 'lucas.ferreira@saasapp.com',
    username: 'lferreira',
    status: 'active',
    role: 'support',
    joinedDate: DateTime(2023, 11, 2),
    lastActive: DateTime(2026, 2, 4),
    plan: 'starter',
  ),
  UserModel(
    avatarUrl: 'assets/images/avatar_9.jpg',
    fullName: 'Isabella Rossi',
    email: 'isabella.rossi@saasapp.com',
    username: 'irossi',
    status: 'active',
    role: 'member',
    joinedDate: DateTime(2023, 11, 15),
    lastActive: DateTime(2026, 2, 1),
    plan: 'pro',
  ),

  UserModel(
    avatarUrl: 'assets/images/avatar_10.jpg',
    fullName: 'Mark Peterson',
    email: 'mark.peterson@saasapp.com',
    username: 'mpeterson',
    status: 'active',
    role: 'member',
    joinedDate: DateTime(2023, 12, 1),
    lastActive: DateTime(2026, 1, 28),
    plan: 'free',
  ),
  UserModel(
    avatarUrl: 'assets/images/avatar_11.jpg',
    fullName: 'Olivia Turner',
    email: 'olivia.turner@saasapp.com',
    username: 'oturner',
    status: 'active',
    role: 'support',
    joinedDate: DateTime(2023, 12, 10),
    lastActive: DateTime(2026, 2, 3),
    plan: 'starter',
  ),
  UserModel(
    avatarUrl: 'assets/images/avatar_1.jpg',
    fullName: 'Benjamin Scott',
    email: 'benjamin.scott@saasapp.com',
    username: 'bscott',
    status: 'suspended',
    role: 'member',
    joinedDate: DateTime(2024, 1, 5),
    lastActive: DateTime(2025, 12, 10),
    plan: 'pro',
  ),
  UserModel(
    avatarUrl: 'assets/images/avatar_2.jpg',
    fullName: 'Yuki Tanaka',
    email: 'yuki.tanaka@saasapp.com',
    username: 'ytanaka',
    status: 'active',
    role: 'member',
    joinedDate: DateTime(2024, 1, 18),
    lastActive: DateTime(2026, 2, 4),
    plan: 'enterprise',
  ),
  UserModel(
    avatarUrl: 'assets/images/avatar_3.jpg',
    fullName: 'Paulo Ribeiro',
    email: 'paulo.ribeiro@saasapp.com',
    username: 'pribeiro',
    status: 'active',
    role: 'support',
    joinedDate: DateTime(2024, 2, 3),
    lastActive: DateTime(2026, 2, 2),
    plan: 'starter',
  ),
  UserModel(
    avatarUrl: 'assets/images/avatar_4.jpg',
    fullName: 'Marta Kowalski',
    email: 'marta.kowalski@saasapp.com',
    username: 'mkowalski',
    status: 'inactive',
    role: 'member',
    joinedDate: DateTime(2024, 2, 14),
    lastActive: DateTime(2025, 10, 5),
    plan: 'free',
  ),
  UserModel(
    avatarUrl: 'assets/images/avatar_5.jpg',
    fullName: 'Chris Adams',
    email: 'chris.adams@saasapp.com',
    username: 'cadams',
    status: 'active',
    role: 'manager',
    joinedDate: DateTime(2024, 3, 1),
    lastActive: DateTime(2026, 2, 3),
    plan: 'pro',
  ),
  UserModel(
    avatarUrl: 'assets/images/avatar_6.jpg',
    fullName: 'Fatima Noor',
    email: 'fatima.noor@saasapp.com',
    username: 'fnoor',
    status: 'active',
    role: 'member',
    joinedDate: DateTime(2024, 3, 12),
    lastActive: DateTime(2026, 2, 1),
    plan: 'free',
  ),
  UserModel(
    avatarUrl: 'assets/images/avatar_7.jpg',
    fullName: 'Jonas Müller',
    email: 'jonas.mueller@saasapp.com',
    username: 'jmueller',
    status: 'banned',
    role: 'member',
    joinedDate: DateTime(2024, 4, 1),
    lastActive: DateTime(2025, 7, 20),
    plan: 'free',
  ),
  UserModel(
    avatarUrl: 'assets/images/avatar_8.jpg',
    fullName: 'Laura Mitchell',
    email: 'laura.mitchell@saasapp.com',
    username: 'lmitchell',
    status: 'active',
    role: 'support',
    joinedDate: DateTime(2024, 4, 15),
    lastActive: DateTime(2026, 2, 4),
    plan: 'pro',
  ),
];
