import 'dart:math';

import 'package:flutter_ademin/ai_reference/ai_reference_models.dart';
import 'package:flutter_ademin/theme/themes.dart';

final List<CountryUserData> liveUserData = [
  CountryUserData('United States', 2450),
  CountryUserData('India', 1820),
  CountryUserData('Indonesia', 1325),
  CountryUserData('Brazil', 980),
  CountryUserData('Germany', 720),
  CountryUserData('Australia', 610),
  CountryUserData('Canada', 540),
  CountryUserData('France', 500),
  CountryUserData('China', 380),
  CountryUserData('Nigeria', 240),
];

final Random _random = Random();

final List<AudienceData> audienceMetrics = List.generate(30, (index) {
  final date = DateTime(2025, 7, index + 1);
  final int users = 1000 + _random.nextInt(500) + (index * 15);
  final int sessions = (users * (1.1 + _random.nextDouble() * 1.0)).toInt();
  final int pageviews = (sessions * (1.2 + _random.nextDouble() * 1.0)).toInt();
  return AudienceData(date, users, pageviews, sessions);
});

final List<AudienceSummary> audienceSummaries = [
  AudienceSummary(value: '7,585', label: 'Users'),
  AudienceSummary(value: '15,585,', label: 'Page Views'),
  AudienceSummary(value: '7,451', label: 'Sesions'),
  AudienceSummary(
    value: '18.92%',
    label: 'Conversion Rate',
    valueColor: () => kSuccessColor,
  ),
];

final List<MiniMetricData> metrics = [
  MiniMetricData.fromRawTrend(
    title: 'Bounce Rate (Avg)',
    value: '47.74%',
    prevLabel: 'vs 66.88% (prev.)',
    change: -28.60,
    rawTrend: [
      10.0,
      22.0,
      34.0,
      35.0,
      55.0,
      60.0,
      45.0,
      30.0,
      30.0,
      49.0,
      15.0,
      20.5,
      48.0,
      47.0,
      46.5,
      50.0,
      30.0,
      15.5,
      20.0,
      45.0,
      44.5,
      16.0,
      10.0,
      60.5,
      45.0,
      23.5,
      46.0,
      46.5,
      47.0,
      35.0,
    ],
    color: () => kInfoColor,
  ),
  MiniMetricData.fromRawTrend(
    title: 'Pageviews (Avg)',
    value: '2.75',
    prevLabel: 'vs 2.19 (prev.)',
    change: 25.57,
    rawTrend: [
      2.2,
      2.3,
      2.2,
      2.4,
      2.3,
      1.8,
      1.0,
      2.6,
      2.5,
      2.7,
      3.0,
      3.2,
      3.5,
      5.0,
      1.0,
      2.8,
      2.7,
      4.0,
      2.5,
      2.4,
      2.5,
      2.6,
      1.7,
      2.1,
      2.7,
      2.72,
      2.73,
      5.74,
      2.75,
      2.75,
    ],
    color: () => kSuccessColor,
  ),
  MiniMetricData.fromRawTrend(
    title: 'New Sessions',
    value: '76.40%',
    prevLabel: 'vs 74.80% (prev.)',
    change: 2.14,
    rawTrend: [
      65.0,
      77.0,
      76.0,
      75.0,
      74.0,
      53.0,
      62.0,
      71.5,
      80.0,
      53.5,
      70.0,
      70.5,
      51.0,
      60.5,
      70.0,
      70.5,
      51.0,
      51.5,
      72.0,
      44.5,
      20.0,
      43.5,
      54.0,
      64.5,
      75.0,
      54.5,
      60.0,
      40.2,
      32.3,
      20.40,
    ],
    color: () => kErrorColor,
  ),
  MiniMetricData.fromRawTrend(
    title: 'Time on Site (Avg)',
    value: '2m:15s',
    prevLabel: 'vs 1m:51s (prev.)',
    change: 21.62,
    rawTrend: [
      120.0,
      140.0,
      100.0,
      150.0,
      90.0,
      130.0,
      110.0,
      98.0,
      115.0,
      120.0,
      125.0,
      130.0,
      120.0,
      135.0,
      125.0,
      130.0,
      135.0,
      80.0,
      130.0,
      135.0,
      78.0,
      145.0,
      135.0,
      67.0,
      80.0,
      90.0,
      78.0,
      90.0,
      150.0,
      135.0,
    ],
    color: () => kSecondaryColor,
  ),
];

final List<UserModel> mockUsers = [
  UserModel(
    avatarUrl: 'assets/images/avatar_1.jpg',
    fullName: 'Daniel Robertson',
    email: 'daniel.robertson@saasapp.com',
    username: 'danielr',
    status: 'active',
    role: 'admin',
    joinedDate: DateTime(2023, 1, 12),
    lastActive: DateTime(2026, 2, 3),
    plan: 'enterprise',
  ),
  UserModel(
    avatarUrl: 'assets/images/avatar_2.jpg',
    fullName: 'Sarah Williams',
    email: 'sarah.williams@saasapp.com',
    username: 'sarahw',
    status: 'active',
    role: 'manager',
    joinedDate: DateTime(2023, 2, 5),
    lastActive: DateTime(2026, 2, 2),
    plan: 'pro',
  ),
  UserModel(
    avatarUrl: 'assets/images/avatar_3.jpg',
    fullName: 'Michael Chen',
    email: 'michael.chen@saasapp.com',
    username: 'mchen',
    status: 'inactive',
    role: 'member',
    joinedDate: DateTime(2023, 3, 10),
    lastActive: DateTime(2025, 11, 12),
    plan: 'free',
  ),
  UserModel(
    avatarUrl: 'assets/images/avatar_4.jpg',
    fullName: 'Alicia Gomez',
    email: 'alicia.gomez@saasapp.com',
    username: 'agomez',
    status: 'active',
    role: 'support',
    joinedDate: DateTime(2023, 3, 18),
    lastActive: DateTime(2026, 2, 1),
    plan: 'starter',
  ),
  UserModel(
    avatarUrl: 'assets/images/avatar_5.jpg',
    fullName: 'Thomas Becker',
    email: 'thomas.becker@saasapp.com',
    username: 'tbecker',
    status: 'suspended',
    role: 'member',
    joinedDate: DateTime(2023, 4, 2),
    lastActive: DateTime(2025, 12, 20),
    plan: 'pro',
  ),
  UserModel(
    avatarUrl: 'assets/images/avatar_6.jpg',
    fullName: 'Nina Petrova',
    email: 'nina.petrova@saasapp.com',
    username: 'npetrova',
    status: 'active',
    role: 'manager',
    joinedDate: DateTime(2023, 4, 15),
    lastActive: DateTime(2026, 2, 3),
    plan: 'enterprise',
  ),
  UserModel(
    avatarUrl: 'assets/images/avatar_7.jpg',
    fullName: "James O'Connor",
    email: 'james.oconnor@saasapp.com',
    username: 'joconnor',
    status: 'active',
    role: 'member',
    joinedDate: DateTime(2023, 5, 1),
    lastActive: DateTime(2026, 1, 30),
    plan: 'starter',
  ),
  UserModel(
    avatarUrl: 'assets/images/avatar_8.jpg',
    fullName: 'Linda Park',
    email: 'linda.park@saasapp.com',
    username: 'lpark',
    status: 'banned',
    role: 'member',
    joinedDate: DateTime(2023, 5, 12),
    lastActive: DateTime(2025, 9, 5),
    plan: 'free',
  ),
  UserModel(
    avatarUrl: 'assets/images/avatar_9.jpg',
    fullName: 'Victor Ivanov',
    email: 'victor.ivanov@saasapp.com',
    username: 'vivanov',
    status: 'active',
    role: 'support',
    joinedDate: DateTime(2023, 6, 3),
    lastActive: DateTime(2026, 2, 4),
    plan: 'pro',
  ),
  UserModel(
    avatarUrl: 'assets/images/avatar_10.jpg',
    fullName: 'Emily Carter',
    email: 'emily.carter@saasapp.com',
    username: 'ecarter',
    status: 'inactive',
    role: 'member',
    joinedDate: DateTime(2023, 6, 20),
    lastActive: DateTime(2025, 10, 12),
    plan: 'free',
  ),
  UserModel(
    avatarUrl: 'assets/images/avatar_11.jpg',
    fullName: 'Robert Kim',
    email: 'robert.kim@saasapp.com',
    username: 'rkim',
    status: 'active',
    role: 'manager',
    joinedDate: DateTime(2023, 7, 2),
    lastActive: DateTime(2026, 2, 3),
    plan: 'enterprise',
  ),
  UserModel(
    avatarUrl: 'assets/images/avatar_1.jpg',
    fullName: 'Hannah Schmidt',
    email: 'hannah.schmidt@saasapp.com',
    username: 'hschmidt',
    status: 'active',
    role: 'member',
    joinedDate: DateTime(2023, 7, 18),
    lastActive: DateTime(2026, 1, 29),
    plan: 'pro',
  ),
  UserModel(
    avatarUrl: 'assets/images/avatar_2.jpg',
    fullName: 'Ahmed Hassan',
    email: 'ahmed.hassan@saasapp.com',
    username: 'ahassan',
    status: 'suspended',
    role: 'support',
    joinedDate: DateTime(2023, 8, 1),
    lastActive: DateTime(2025, 12, 2),
    plan: 'starter',
  ),
  UserModel(
    avatarUrl: 'assets/images/avatar_3.jpg',
    fullName: 'Julia Novak',
    email: 'julia.novak@saasapp.com',
    username: 'jnovak',
    status: 'active',
    role: 'member',
    joinedDate: DateTime(2023, 8, 9),
    lastActive: DateTime(2026, 2, 1),
    plan: 'pro',
  ),
  UserModel(
    avatarUrl: 'assets/images/avatar_4.jpg',
    fullName: 'Diego Morales',
    email: 'diego.morales@saasapp.com',
    username: 'dmorales',
    status: 'active',
    role: 'support',
    joinedDate: DateTime(2023, 9, 3),
    lastActive: DateTime(2026, 2, 4),
    plan: 'enterprise',
  ),
  UserModel(
    avatarUrl: 'assets/images/avatar_5.jpg',
    fullName: 'Sophia Laurent',
    email: 'sophia.laurent@saasapp.com',
    username: 'slaurent',
    status: 'banned',
    role: 'member',
    joinedDate: DateTime(2023, 9, 15),
    lastActive: DateTime(2025, 8, 19),
    plan: 'free',
  ),
  UserModel(
    avatarUrl: 'assets/images/avatar_6.jpg',
    fullName: 'Kevin Brown',
    email: 'kevin.brown@saasapp.com',
    username: 'kbrown',
    status: 'active',
    role: 'manager',
    joinedDate: DateTime(2023, 10, 1),
    lastActive: DateTime(2026, 2, 3),
    plan: 'pro',
  ),
  UserModel(
    avatarUrl: 'assets/images/avatar_7.jpg',
    fullName: 'Natalie Wong',
    email: 'natalie.wong@saasapp.com',
    username: 'nwong',
    status: 'inactive',
    role: 'member',
    joinedDate: DateTime(2023, 10, 10),
    lastActive: DateTime(2025, 11, 1),
    plan: 'free',
  ),
  UserModel(
    avatarUrl: 'assets/images/avatar_8.jpg',
    fullName: 'Lucas Ferreira',
    email: 'lucas.ferreira@saasapp.com',
    username: 'lferreira',
    status: 'active',
    role: 'support',
    joinedDate: DateTime(2023, 11, 2),
    lastActive: DateTime(2026, 2, 4),
    plan: 'starter',
  ),
  UserModel(
    avatarUrl: 'assets/images/avatar_9.jpg',
    fullName: 'Isabella Rossi',
    email: 'isabella.rossi@saasapp.com',
    username: 'irossi',
    status: 'active',
    role: 'member',
    joinedDate: DateTime(2023, 11, 15),
    lastActive: DateTime(2026, 2, 1),
    plan: 'pro',
  ),
  UserModel(
    avatarUrl: 'assets/images/avatar_10.jpg',
    fullName: 'Mark Peterson',
    email: 'mark.peterson@saasapp.com',
    username: 'mpeterson',
    status: 'active',
    role: 'member',
    joinedDate: DateTime(2023, 12, 1),
    lastActive: DateTime(2026, 1, 28),
    plan: 'free',
  ),
  UserModel(
    avatarUrl: 'assets/images/avatar_11.jpg',
    fullName: 'Olivia Turner',
    email: 'olivia.turner@saasapp.com',
    username: 'oturner',
    status: 'active',
    role: 'support',
    joinedDate: DateTime(2023, 12, 10),
    lastActive: DateTime(2026, 2, 3),
    plan: 'starter',
  ),
  UserModel(
    avatarUrl: 'assets/images/avatar_1.jpg',
    fullName: 'Benjamin Scott',
    email: 'benjamin.scott@saasapp.com',
    username: 'bscott',
    status: 'suspended',
    role: 'member',
    joinedDate: DateTime(2024, 1, 5),
    lastActive: DateTime(2025, 12, 10),
    plan: 'pro',
  ),
  UserModel(
    avatarUrl: 'assets/images/avatar_2.jpg',
    fullName: 'Yuki Tanaka',
    email: 'yuki.tanaka@saasapp.com',
    username: 'ytanaka',
    status: 'active',
    role: 'member',
    joinedDate: DateTime(2024, 1, 18),
    lastActive: DateTime(2026, 2, 4),
    plan: 'enterprise',
  ),
  UserModel(
    avatarUrl: 'assets/images/avatar_3.jpg',
    fullName: 'Paulo Ribeiro',
    email: 'paulo.ribeiro@saasapp.com',
    username: 'pribeiro',
    status: 'active',
    role: 'support',
    joinedDate: DateTime(2024, 2, 3),
    lastActive: DateTime(2026, 2, 2),
    plan: 'starter',
  ),
  UserModel(
    avatarUrl: 'assets/images/avatar_4.jpg',
    fullName: 'Marta Kowalski',
    email: 'marta.kowalski@saasapp.com',
    username: 'mkowalski',
    status: 'inactive',
    role: 'member',
    joinedDate: DateTime(2024, 2, 14),
    lastActive: DateTime(2025, 10, 5),
    plan: 'free',
  ),
  UserModel(
    avatarUrl: 'assets/images/avatar_5.jpg',
    fullName: 'Chris Adams',
    email: 'chris.adams@saasapp.com',
    username: 'cadams',
    status: 'active',
    role: 'manager',
    joinedDate: DateTime(2024, 3, 1),
    lastActive: DateTime(2026, 2, 3),
    plan: 'pro',
  ),
  UserModel(
    avatarUrl: 'assets/images/avatar_6.jpg',
    fullName: 'Fatima Noor',
    email: 'fatima.noor@saasapp.com',
    username: 'fnoor',
    status: 'active',
    role: 'member',
    joinedDate: DateTime(2024, 3, 12),
    lastActive: DateTime(2026, 2, 1),
    plan: 'free',
  ),
  UserModel(
    avatarUrl: 'assets/images/avatar_7.jpg',
    fullName: 'Jonas Muller',
    email: 'jonas.mueller@saasapp.com',
    username: 'jmueller',
    status: 'banned',
    role: 'member',
    joinedDate: DateTime(2024, 4, 1),
    lastActive: DateTime(2025, 7, 20),
    plan: 'free',
  ),
  UserModel(
    avatarUrl: 'assets/images/avatar_8.jpg',
    fullName: 'Laura Mitchell',
    email: 'laura.mitchell@saasapp.com',
    username: 'lmitchell',
    status: 'active',
    role: 'support',
    joinedDate: DateTime(2024, 4, 15),
    lastActive: DateTime(2026, 2, 4),
    plan: 'pro',
  ),
];
