// Data Mockups

import 'package:flutkit_ademin/demo/page/notifications/notifications_models.dart';

List<AppNotification> mockNotifications = [
  AppNotification(
    id: "1",
    title: "New order received",
    description: "Emma Wilson placed order ORD-7891 for \$299.00",
    time: DateTime.now().subtract(const Duration(minutes: 2)),
    type: NotificationType.order,
    status: NotificationStatus.unread,
  ),
  AppNotification(
    id: "2",
    title: "Payment processed",
    description: "Payment of \$1,499.00 from Sofia Garcia confirmed",
    time: DateTime.now().subtract(const Duration(minutes: 15)),
    type: NotificationType.payment,
    status: NotificationStatus.unread,
  ),
  AppNotification(
    id: "3",
    title: "New customer signup",
    description: "James Chen created an account",
    time: DateTime.now().subtract(const Duration(hours: 1)),
    type: NotificationType.user,
    status: NotificationStatus.unread,
  ),
  AppNotification(
    id: "4",
    title: "Order shipped",
    description: "ORD-7889 has been shipped to Sofia Garcia",
    time: DateTime.now().subtract(const Duration(hours: 2)),
    type: NotificationType.order,
    status: NotificationStatus.read,
  ),
  AppNotification(
    id: "5",
    title: "System update",
    description: "Dashboard v2.1 has been deployed successfully",
    time: DateTime.now().subtract(const Duration(hours: 3)),
    type: NotificationType.system,
    status: NotificationStatus.read,
  ),

  // ===== tambahan 15 data =====
  AppNotification(
    id: "6",
    title: "Refund issued",
    description: "Refund of \$120.00 sent to Michael Brown",
    time: DateTime.now().subtract(const Duration(hours: 5)),
    type: NotificationType.payment,
    status: NotificationStatus.unread,
  ),
  AppNotification(
    id: "7",
    title: "New order received",
    description: "Anna Smith placed order ORD-7895",
    time: DateTime.now().subtract(const Duration(hours: 6)),
    type: NotificationType.order,
    status: NotificationStatus.read,
  ),
  AppNotification(
    id: "8",
    title: "Password changed",
    description: "Your password was updated successfully",
    time: DateTime.now().subtract(const Duration(hours: 7)),
    type: NotificationType.system,
    status: NotificationStatus.read,
  ),
  AppNotification(
    id: "9",
    title: "New customer signup",
    description: "David Lee created an account",
    time: DateTime.now().subtract(const Duration(hours: 8)),
    type: NotificationType.user,
    status: NotificationStatus.unread,
  ),
  AppNotification(
    id: "10",
    title: "Payment failed",
    description: "Payment attempt from Olivia White failed",
    time: DateTime.now().subtract(const Duration(hours: 9)),
    type: NotificationType.payment,
    status: NotificationStatus.unread,
  ),
  AppNotification(
    id: "11",
    title: "Order delivered",
    description: "ORD-7880 delivered successfully",
    time: DateTime.now().subtract(const Duration(hours: 10)),
    type: NotificationType.order,
    status: NotificationStatus.read,
  ),
  AppNotification(
    id: "12",
    title: "System maintenance",
    description: "Scheduled maintenance at 2 AM",
    time: DateTime.now().subtract(const Duration(hours: 11)),
    type: NotificationType.system,
    status: NotificationStatus.read,
  ),
  AppNotification(
    id: "13",
    title: "New customer signup",
    description: "Sophia Martinez joined the platform",
    time: DateTime.now().subtract(const Duration(hours: 12)),
    type: NotificationType.user,
    status: NotificationStatus.unread,
  ),
  AppNotification(
    id: "14",
    title: "Payment received",
    description: "You received \$250.00 from Daniel Kim",
    time: DateTime.now().subtract(const Duration(hours: 13)),
    type: NotificationType.payment,
    status: NotificationStatus.read,
  ),
  AppNotification(
    id: "15",
    title: "Order canceled",
    description: "ORD-7892 has been canceled",
    time: DateTime.now().subtract(const Duration(hours: 14)),
    type: NotificationType.order,
    status: NotificationStatus.unread,
  ),
  AppNotification(
    id: "16",
    title: "Security alert",
    description: "New login detected from another device",
    time: DateTime.now().subtract(const Duration(hours: 15)),
    type: NotificationType.system,
    status: NotificationStatus.unread,
  ),
  AppNotification(
    id: "17",
    title: "New message",
    description: "You received a new support message",
    time: DateTime.now().subtract(const Duration(hours: 16)),
    type: NotificationType.system,
    status: NotificationStatus.read,
  ),
  AppNotification(
    id: "18",
    title: "New order received",
    description: "Chris Evans placed order ORD-7901",
    time: DateTime.now().subtract(const Duration(hours: 17)),
    type: NotificationType.order,
    status: NotificationStatus.unread,
  ),
  AppNotification(
    id: "19",
    title: "Payment refunded",
    description: "Refund issued to Emily Clark",
    time: DateTime.now().subtract(const Duration(hours: 18)),
    type: NotificationType.payment,
    status: NotificationStatus.read,
  ),
  AppNotification(
    id: "20",
    title: "Account verified",
    description: "Your account has been successfully verified",
    time: DateTime.now().subtract(const Duration(hours: 20)),
    type: NotificationType.user,
    status: NotificationStatus.read,
  ),
];
