// mock up data of Project
import 'package:flutter_ademin/demo/app/project/project_models.dart';

final List<Project> projects = [
  Project(
    title: 'Design & Developing New Project',
    totalTasks: 22,
    completedTasks: 18,
    teamMemberAvatars: [
      'assets/images/avatar_1.jpg',
      'assets/images/avatar_2.jpg',
      'assets/images/avatar_3.jpg',
      'assets/images/avatar_4.jpg',
      'assets/images/avatar_5.jpg',
      'assets/images/avatar_6.jpg',
      'assets/images/avatar_7.jpg',
      'assets/images/avatar_8.jpg',
    ],
    priority: 'Low',
    description:
        'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nisi maiores similique tempore.',
    assignedDate: DateTime(2023, 5, 24),
    dueDate: DateTime(2023, 7, 12),
  ),
  Project(
    title: 'UI Review & QA Testing',
    totalTasks: 15,
    completedTasks: 10,
    teamMemberAvatars: [
      'assets/images/avatar_2.jpg',
      'assets/images/avatar_3.jpg',
      'assets/images/avatar_4.jpg',
      'assets/images/avatar_6.jpg',
      'assets/images/avatar_7.jpg',
      'assets/images/avatar_8.jpg',
    ],
    priority: 'Medium',
    description: 'Review UI components and test across multiple devices.',
    assignedDate: DateTime(2023, 6, 10),
    dueDate: DateTime(2023, 7, 30),
  ),
  Project(
    title: 'Implement User Authentication',
    totalTasks: 8,
    completedTasks: 7,
    teamMemberAvatars: [
      'assets/images/avatar_6.jpg',
      'assets/images/avatar_7.jpg',
      'assets/images/avatar_8.jpg',
    ],
    priority: 'High',
    description: 'Develop secure user login and registration functionalities.',
    assignedDate: DateTime(2023, 7, 1),
    dueDate: DateTime(2023, 7, 20),
  ),
  Project(
    title: 'Database Migration to New Server',
    totalTasks: 3,
    completedTasks: 2,
    teamMemberAvatars: [
      'assets/images/avatar_9.jpg',
      'assets/images/avatar_10.jpg',
      'assets/images/avatar_11.jpg',
      'assets/images/avatar_1.jpg',
      'assets/images/avatar_5.jpg',
      'assets/images/avatar_6.jpg',
    ],
    priority: 'High',
    description: 'Migrate existing database to the new server infrastructure.',
    assignedDate: DateTime(2023, 7, 15),
    dueDate: DateTime(2023, 8, 5),
  ),
  Project(
    title: 'Develop RESTful API Endpoints',
    totalTasks: 12,
    completedTasks: 6,
    teamMemberAvatars: [
      'assets/images/avatar_10.jpg',
      'assets/images/avatar_11.jpg',
      'assets/images/avatar_1.jpg',
      'assets/images/avatar_6.jpg',
      'assets/images/avatar_7.jpg',
      'assets/images/avatar_8.jpg',
    ],
    priority: 'Medium',
    description: 'Create API endpoints for mobile and web applications.',
    assignedDate: DateTime(2023, 8, 1),
    dueDate: DateTime(2023, 8, 25),
  ),
  Project(
    title: 'Integrate Third-Party Payment Gateway',
    totalTasks: 5,
    completedTasks: 4,
    teamMemberAvatars: [
      'assets/images/avatar_11.jpg',
      'assets/images/avatar_1.jpg',
      'assets/images/avatar_6.jpg',
      'assets/images/avatar_7.jpg',
      'assets/images/avatar_8.jpg',
    ],
    priority: 'High',
    description: 'Integrate Stripe for processing online payments.',
    assignedDate: DateTime(2023, 8, 10),
    dueDate: DateTime(2023, 8, 30),
  ),
  Project(
    title: 'Mobile App Redesign - iOS',
    totalTasks: 18,
    completedTasks: 9,
    teamMemberAvatars: [
      'assets/images/avatar_6.jpg',
      'assets/images/avatar_7.jpg',
      'assets/images/avatar_8.jpg',
      'assets/images/avatar_1.jpg',
      'assets/images/avatar_2.jpg',
      'assets/images/avatar_3.jpg',
      'assets/images/avatar_4.jpg',
      'assets/images/avatar_5.jpg',
    ],
    priority: 'Medium',
    description: 'Redesign the user interface and experience for the iOS app.',
    assignedDate: DateTime(2023, 9, 1),
    dueDate: DateTime(2023, 10, 15),
  ),
  Project(
    title: 'Implement Push Notification Service',
    totalTasks: 7,
    completedTasks: 5,
    teamMemberAvatars: [
      'assets/images/avatar_6.jpg',
      'assets/images/avatar_7.jpg',
      'assets/images/avatar_8.jpg',
    ],
    priority: 'Medium',
    description: 'Set up push notifications for important updates and alerts.',
    assignedDate: DateTime(2023, 9, 15),
    dueDate: DateTime(2023, 10, 5),
  ),
  Project(
    title: 'Develop Admin Dashboard Features',
    totalTasks: 10,
    completedTasks: 8,
    teamMemberAvatars: [
      'assets/images/avatar_6.jpg',
      'assets/images/avatar_7.jpg',
      'assets/images/avatar_2.jpg',
      'assets/images/avatar_3.jpg',
      'assets/images/avatar_4.jpg',
    ],
    priority: 'High',
    description: 'Add new features to the administrator dashboard.',
    assignedDate: DateTime(2023, 10, 1),
    dueDate: DateTime(2023, 10, 20),
  ),
  Project(
    title: 'Website Performance Optimization',
    totalTasks: 6,
    completedTasks: 3,
    teamMemberAvatars: ['assets/images/avatar_4.jpg'],
    priority: 'Medium',
    description: 'Improve the loading speed and performance of the website.',
    assignedDate: DateTime(2023, 10, 10),
    dueDate: DateTime(2023, 10, 30),
  ),
  Project(
    title: 'Create Onboarding Tutorial for New Users',
    totalTasks: 4,
    completedTasks: 4,
    teamMemberAvatars: [
      'assets/images/avatar_7.jpg',
      'assets/images/avatar_1.jpg',
      'assets/images/avatar_6.jpg',
    ],
    priority: 'Low',
    description:
        'Design and develop an interactive onboarding tutorial, which will involve creating step-by-step guides and interactive elements.',
    assignedDate: DateTime(2023, 11, 1),
    dueDate: DateTime(2023, 11, 15),
  ),
  Project(
    title: 'Implement Email Marketing Campaign',
    totalTasks: 9,
    completedTasks: 6,
    teamMemberAvatars: [
      'assets/images/avatar_9.jpg',
      'assets/images/avatar_4.jpg',
    ],
    priority: 'Medium',
    description: 'Create and schedule email marketing campaigns.',
    assignedDate: DateTime(2023, 11, 10),
    dueDate: DateTime(2023, 11, 30),
  ),
  Project(
    title: 'Develop Internal Reporting System',
    totalTasks: 11,
    completedTasks: 7,
    teamMemberAvatars: [
      'assets/images/avatar_3.jpg',
      'assets/images/avatar_9.jpg',
    ],
    priority: 'High',
    description: 'Build a system for generating internal reports.',
    assignedDate: DateTime(2023, 12, 1),
    dueDate: DateTime(2023, 12, 22),
  ),
  Project(
    title: 'Update Company Branding Guidelines',
    totalTasks: 2,
    completedTasks: 2,
    teamMemberAvatars: [
      'assets/images/avatar_8.jpg',
      'assets/images/avatar_1.jpg',
    ],
    priority: 'Low',
    description: 'Review and update the company\'s branding guidelines.',
    assignedDate: DateTime(2023, 12, 15),
    dueDate: DateTime(2023, 12, 25),
  ),
  Project(
    title: 'Enhance Search Functionality',
    totalTasks: 14,
    completedTasks: 8,
    teamMemberAvatars: [
      'assets/images/avatar_11.jpg',
      'assets/images/avatar_10.jpg',
      'assets/images/avatar_4.jpg',
    ],
    priority: 'Medium',
    description: 'Improve the accuracy and speed of the search feature.',
    assignedDate: DateTime(2024, 1, 5),
    dueDate: DateTime(2024, 1, 28),
  ),
  Project(
    title: 'Implement Two-Factor Authentication',
    totalTasks: 6,
    completedTasks: 5,
    teamMemberAvatars: ['assets/images/avatar_1.jpg'],
    priority: 'High',
    description: 'Add two-factor authentication for enhanced security.',
    assignedDate: DateTime(2024, 1, 20),
    dueDate: DateTime(2024, 2, 10),
  ),
  Project(
    title: 'Develop Customer Feedback Form',
    totalTasks: 3,
    completedTasks: 3,
    teamMemberAvatars: [
      'assets/images/avatar_7.jpg',
      'assets/images/avatar_9.jpg',
    ],
    priority: 'Low',
    description: 'Create a form for collecting customer feedback.',
    assignedDate: DateTime(2024, 2, 1),
    dueDate: DateTime(2024, 2, 15),
  ),
  Project(
    title: 'Social Media Integration',
    totalTasks: 10,
    completedTasks: 6,
    teamMemberAvatars: [
      'assets/images/avatar_1.jpg',
      'assets/images/avatar_6.jpg',
    ],
    priority: 'Medium',
    description: 'Integrate social media sharing and login options.',
    assignedDate: DateTime(2024, 2, 15),
    dueDate: DateTime(2024, 3, 10),
  ),
  Project(
    title: 'Implement Real-time Chat Feature',
    totalTasks: 7,
    completedTasks: 4,
    teamMemberAvatars: [
      'assets/images/avatar_7.jpg',
      'assets/images/avatar_3.jpg',
      'assets/images/avatar_8.jpg',
    ],
    priority: 'Medium',
    description: 'Develop a real-time chat functionality for users.',
    assignedDate: DateTime(2024, 3, 1),
    dueDate: DateTime(2024, 3, 25),
  ),
  Project(
    title: 'Update Terms and Conditions',
    totalTasks: 1,
    completedTasks: 1,
    teamMemberAvatars: ['assets/images/avatar_10.jpg'],
    priority: 'Low',
    description: 'Review and update the website\'s terms and conditions.',
    assignedDate: DateTime(2024, 3, 15),
    dueDate: DateTime(2024, 3, 22),
  ),
  Project(
    title: 'Improve Error Handling and Logging',
    totalTasks: 9,
    completedTasks: 5,
    teamMemberAvatars: [
      'assets/images/avatar_6.jpg',
      'assets/images/avatar_8.jpg',
    ],
    priority: 'High',
    description: 'Enhance error handling and implement better logging.',
    assignedDate: DateTime(2024, 4, 1),
    dueDate: DateTime(2024, 4, 22),
  ),
  Project(
    title: 'Develop Interactive Data Visualization',
    totalTasks: 12,
    completedTasks: 7,
    teamMemberAvatars: [
      'assets/images/avatar_7.jpg',
      'assets/images/avatar_3.jpg',
      'assets/images/avatar_1.jpg',
    ],
    priority: 'Medium',
    description: 'Create interactive charts and graphs for data analysis.',
    assignedDate: DateTime(2024, 4, 15),
    dueDate: DateTime(2024, 5, 10),
  ),
];

final mockProjectDatas = ProjectDetails(
  id: '5',
  title: 'Flutter Project Management App',
  client: 'Sun Digital Media Corp',
  description:
      "Develop a comprehensive and intuitive mobile application using the Flutter framework to streamline the management of tasks, milestones, and teams for enhanced project collaboration and individual productivity. This application will provide a unified platform for users to create, assign, track, and monitor tasks with detailed descriptions, due dates, priority levels, and assigned team members, ensuring clarity and accountability across all project activities. The milestone management feature will enable users to define key project checkpoints, visualize progress against these critical points, and receive timely notifications regarding upcoming or overdue milestones, facilitating proactive risk management and on-time project delivery. Furthermore, the application will incorporate robust team management capabilities, allowing project leaders to organize team members into specific project groups, assign roles and responsibilities, and facilitate seamless communication through integrated features such as in-app messaging or direct links to other communication platforms. Real-time updates and synchronized data across all user devices will ensure that every team member has access to the latest project information, fostering transparency and efficient collaboration. The application will also offer customizable views and dashboards, allowing users to personalize their experience and focus on the information most relevant to their roles and responsibilities, including visual progress indicators for tasks and milestones,Burndown charts for tracking overall project progress, and customizable notification settings to manage alerts effectively. Advanced features such as file sharing, dependency tracking between tasks, and integration with calendar applications will further enhance the application's utility for managing complex projects. The user interface will be designed with a focus on simplicity and ease of use, adhering to modern UI/UX principles to ensure a seamless and engaging user experience across both Android and iOS platforms, leveraging Flutter's cross-platform capabilities for efficient development and deployment. The application will also incorporate user authentication and authorization mechanisms to ensure data security and privacy, with role-based access control to manage sensitive project information. Future enhancements may include features such as time tracking, resource allocation, and reporting functionalities to provide a holistic project management solution.",
  bgImage: 'assets/images/profile_bg.jpg',
  status: 'inProgress',
  priority: 'high',
  dateCreated: DateTime(2024, 11, 24),
  startDate: DateTime(2024, 12, 1),
  endDate: DateTime(2025, 6, 1),
  progress: 0.45,
  billingType: 'Task Hours',
  tags: ['Flutter', 'Mobile', 'PM', 'UI/UX'],
  members: [
    Member(
      id: 'm1',
      name: 'Umar Hamzah',
      role: 'Project Manager',
      avatarUrl: 'assets/images/avatar_2.jpg',
    ),
    Member(
      id: 'm2',
      name: 'Bob Smith',
      role: 'Flutter Developer',
      avatarUrl: 'assets/images/avatar_3.jpg',
    ),
    Member(
      id: 'm3',
      name: 'Charlie Davis',
      role: 'UI Designer',
      avatarUrl: 'assets/images/avatar_4.jpg',
    ),
    Member(
      id: 'm4',
      name: 'Diana Miller',
      role: 'Backend Developer',
      avatarUrl: 'assets/images/avatar_5.jpg',
    ),
    Member(
      id: 'm5',
      name: 'Ethan White',
      role: 'QA Engineer',
      avatarUrl: 'assets/images/avatar_6.jpg',
    ),
    Member(
      id: 'm6',
      name: 'Fiona Green',
      role: 'Business Analyst',
      avatarUrl: 'assets/images/avatar_7.jpg',
    ),
    Member(
      id: 'm7',
      name: 'George Brown',
      role: 'DevOps Engineer',
      avatarUrl: 'assets/images/avatar_8.jpg',
    ),
    Member(
      id: 'm8',
      name: 'Hannah Black',
      role: 'Mobile Developer',
      avatarUrl: 'assets/images/avatar_9.jpg',
    ),
    Member(
      id: 'm9',
      name: 'Ian Gray',
      role: 'UX Researcher',
      avatarUrl: 'assets/images/avatar_10.jpg',
    ),
    Member(
      id: 'm10',
      name: 'Jane Blue',
      role: 'Technical Lead',
      avatarUrl: 'assets/images/avatar_11.jpg',
    ),
  ],
  milestones: [
    ProjectMilestone(
      id: 'ms1',
      title: 'Project Setup',
      description: 'Initialize repo, setup CI/CD, and dependencies.',
      dueDate: DateTime(2024, 12, 10),
      isCompleted: true,
    ),
    ProjectMilestone(
      id: 'ms2',
      title: 'Task Management Module',
      description: 'Create UI and logic for managing tasks.',
      dueDate: DateTime(2025, 1, 10),
      isCompleted: false,
    ),
  ],
  tasks: [
    ProjectTask(
      id: 't1',
      title: 'Design Dashboard UI',
      description:
          'Create dashboard layout in pptxma. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.\nSed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?',
      priority: 'medium',
      status: 'inProgress',
      startDate: DateTime(2024, 9, 11),
      dueDate: DateTime(2024, 12, 5),
      assignedMemberIds: ['m3', 'm4', 'm5'],
      tags: ['UI', 'UI/UX', 'Design'],
      attachmentIds: ['a3', 'a17', 'a24', 'a29', 'a6'],
      activityIds: ['act3', 'act8', 'act12', 'act18', 'act20'],
      discussionIds: ['d4', 'd14', 'd21', 'd6', 'd18'],
      checklistIds: ['c1', 'c2', 'c3', 'c5', 'c13'],
      discussionCount: 5,
      attachmentCount: 5,
    ),
    ProjectTask(
      id: 't2',
      title: 'Create Login Screen',
      description:
          'Implement email/password login UI and logic. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.\nSed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?',
      priority: 'high',
      status: 'inProgress',
      startDate: DateTime(2024, 10, 12),
      dueDate: DateTime(2024, 12, 15),
      assignedMemberIds: ['m1', 'm5', 'm6'],
      tags: ['Email', 'UI', 'Authentication'],
      attachmentIds: ['a1', 'a3', 'a5', 'a9', 'a7'],
      activityIds: ['act1', 'act7', 'act16', 'act2', 'act5'],
      discussionIds: ['d1', 'd2', 'd11', 'd12', 'd23'],
      checklistIds: ['c1', 'c2', 'c3', 'c9', 'c11'],
      discussionCount: 5,
      attachmentCount: 5,
    ),

    ProjectTask(
      id: 't3',
      title: 'Implement API Integration',
      description:
          'Connect frontend to backend API endpoints. To establish a seamless data flow within the application architecture, the developer is responsible for connecting the frontend user interface to the specified backend API endpoints. This integration serves as the primary communication bridge, enabling the client-side environment to interact with server-side logic and persistent database storage.\nThe implementation begins by configuring a centralized HTTP client service—utilizing either the native Fetch API or the Axios library—to manage outgoing requests. For each feature, the developer must map the frontend actions to their corresponding RESTful routes, ensuring that the correct HTTP verbs (GET, POST, PUT, DELETE) are utilized. Precision is required when defining request parameters, query strings, and body payloads to match the backends expected schema.\nFurthermore, this task involves the rigorous setup of request and response interceptors. These are necessary to inject Authentication headers (such as Bearer tokens) into outgoing calls and to handle global status codes. The developer must implement structured asynchronous logic (using async/await) to manage the lifecycle of a request, including the transition of application states from "loading" to "success" or "error."',
      priority: 'high',
      status: 'notStarted',
      startDate: DateTime(2024, 11, 12),
      dueDate: DateTime(2024, 12, 20),
      assignedMemberIds: ['m1', 'm8'],
      tags: ['UI', 'pptxma', 'Design'],
      attachmentIds: ['a4', 'a9', 'a11', 'a21', 'a26', 'a30'],
      activityIds: ['act4', 'act9', 'act14', 'act22', 'act25'],
      discussionIds: ['d3', 'd9', 'd13', 'd15', 'd29', 'd22'],
      checklistIds: ['c7', 'c8', 'c10', 'c23', 'c26'],
      discussionCount: 6,
      attachmentCount: 6,
    ),
    ProjectTask(
      id: 't4',
      title: 'Write Unit Tests',
      description:
          'Develop unit tests for core application logic. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.\nSed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?',
      priority: 'medium',
      status: 'notStarted',
      startDate: DateTime(2024, 11, 18),
      dueDate: DateTime(2025, 1, 5),
      assignedMemberIds: ['m2', 'm7'],
      tags: ['testing', 'Unit Test', 'Quality'],
      attachmentIds: ['a5', 'a12', 'a15', 'a22', 'a28'],
      activityIds: ['act6', 'act11', 'act17', 'act23', 'act28'],
      discussionIds: ['d6', 'd16', 'd26', 'd5', 'd10'],
      checklistIds: ['c12', 'c28', 'c17', 'c20', 'c5'],
      discussionCount: 5,
      attachmentCount: 5,
    ),
    ProjectTask(
      id: 't5',
      title: 'User Profile Page',
      description:
          'Develop the user profile interface. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.\nSed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?',
      priority: 'medium',
      status: 'inProgress',
      startDate: DateTime(2024, 9, 22),
      dueDate: DateTime(2024, 12, 25),
      assignedMemberIds: ['m5'],
      tags: ['UI', 'User Profile', 'Frontend'],
      attachmentIds: ['a6', 'a10', 'a15', 'a20', 'a24'],
      activityIds: ['act1', 'act2', 'act3', 'act4', 'act5'],
      discussionIds: ['d4', 'd11', 'd12', 'd21', 'd24'],
      checklistIds: ['c13', 'c14', 'c25', 'c2', 'c3'],
      discussionCount: 5,
      attachmentCount: 5,
    ),
    ProjectTask(
      id: 't6',
      title: 'Implement Settings Screen',
      description:
          'Create UI for application settings. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.\nSed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?',
      priority: 'low',
      status: 'testing',
      startDate: DateTime(2024, 11, 19),
      dueDate: DateTime(2025, 1, 15),
      assignedMemberIds: ['m1', 'm9'],
      tags: ['UI', 'Settings', 'Frontend'],
      attachmentIds: ['a7', 'a18', 'a23', 'a27', 'a2'],
      activityIds: ['act10', 'act15', 'act19', 'act24', 'act29'],
      discussionIds: ['d18', 'd19', 'd27', 'd1', 'd7'],
      checklistIds: ['c4', 'c18', 'c21', 'c27', 'c29'],
      discussionCount: 5,
      attachmentCount: 5,
    ),
    ProjectTask(
      id: 't7',
      title: 'Database Schema Design',
      description:
          'Design the application database schema. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.\nSed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?',
      priority: 'high',
      status: 'completed',
      startDate: DateTime(2024, 10, 15),
      dueDate: DateTime(2024, 11, 10),
      assignedMemberIds: ['m1', 'm3'],
      tags: ['Database', 'Schema', 'Design'],
      attachmentIds: ['a8', 'a11', 'a21', 'a30', 'a4', 'a22'],
      activityIds: ['act1', 'act7', 'act16', 'act21', 'act30'],
      discussionIds: ['d9', 'd20', 'd25', 'd30', 'd5', 'd15'],
      checklistIds: ['c7', 'c17', 'c19', 'c10', 'c30'],
      discussionCount: 6,
      attachmentCount: 6,
    ),
    ProjectTask(
      id: 't8',
      title: 'Backend Development',
      description:
          'Develop the backend API using Node.js. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.\nSed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?',
      priority: 'high',
      status: 'inProgress',
      startDate: DateTime(2024, 12, 11),
      dueDate: DateTime(2025, 1, 10),
      assignedMemberIds: ['m1', 'm4', 'm7'],
      tags: ['Backend', 'API', 'Node.js'],
      attachmentIds: ['a9', 'a20', 'a23', 'a28', 'a30', 'a4', 'a11'],
      activityIds: ['act5', 'act10', 'act15', 'act20', 'act25', 'act30'],
      discussionIds: ['d5', 'd15', 'd25', 'd30', 'd13', 'd20'],
      checklistIds: ['c5', 'c7', 'c8', 'c12', 'c17', 'c20'],
      discussionCount: 6,
      attachmentCount: 7,
    ),
    ProjectTask(
      id: 't9',
      title: 'Create Onboarding Flow',
      description:
          'Design and implement the user onboarding process. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.\nSed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?',
      priority: 'medium',
      status: 'awaitFeedback',
      startDate: DateTime(2024, 11, 20),
      dueDate: DateTime(2025, 1, 20),
      assignedMemberIds: ['m3', 'm9'],
      tags: ['UX', 'Onboarding', 'Frontend'],
      attachmentIds: ['a10', 'a6', 'a1', 'a25', 'a14'],
      activityIds: ['act2', 'act8', 'act14', 'act20', 'act26'],
      discussionIds: ['d4', 'd10', 'd20', 'd30', 'd15'],
      checklistIds: ['c1', 'c9', 'c25', 'c15', 'c21'],
      discussionCount: 5,
      attachmentCount: 5,
    ),
    ProjectTask(
      id: 't10',
      title: 'Implement Data Validation',
      description:
          'Add validation for user inputs. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.\nSed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?',
      priority: 'medium',
      status: 'inProgress',
      startDate: DateTime(2024, 10, 5),
      dueDate: DateTime(2024, 12, 30),
      assignedMemberIds: ['m2', 'm6'],
      tags: ['Validation', 'Data', 'Frontend'],
      attachmentIds: ['a11', 'a23', 'a5', 'a21', 'a1'],
      activityIds: ['act3', 'act9', 'act15', 'act21', 'act27'],
      discussionIds: ['d1', 'd3', 'd11', 'd19', 'd29'],
      checklistIds: ['c9', 'c10', 'c11', 'c26', 'c12'],
      discussionCount: 5,
      attachmentCount: 5,
    ),
    ProjectTask(
      id: 't11',
      title: 'Write Integration Tests',
      description:
          'Develop integration tests for API endpoints. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.\nSed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?',
      priority: 'high',
      status: 'awaitFeedback',
      startDate: DateTime(2024, 12, 31),
      dueDate: DateTime(2025, 2, 5),
      assignedMemberIds: ['m1', 'm2', 'm4'],
      tags: ['testing', 'Integration Test', 'API'],
      attachmentIds: ['a12', 'a22', 'a26', 'a30', 'a4'],
      activityIds: ['act4', 'act11', 'act18', 'act25', 'act2'],
      discussionIds: ['d3', 'd13', 'd22', 'd26', 'd15'],
      checklistIds: ['c12', 'c28', 'c30', 'c17', 'c8'],
      discussionCount: 5,
      attachmentCount: 5,
    ),
    ProjectTask(
      id: 't12',
      title: 'Deployment to Staging',
      description:
          'Deploy the application to the staging environment. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.\nSed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?',
      priority: 'medium',
      status: 'completed',
      startDate: DateTime(2025, 1, 12),
      dueDate: DateTime(2025, 2, 10),
      assignedMemberIds: ['m6', 'm10'],
      tags: ['Deployment', 'Staging', 'DevOps'],
      attachmentIds: ['a13', 'a26', 'a4', 'a22', 'a9'],
      activityIds: ['act5', 'act12', 'act19', 'act26', 'act3'],
      discussionIds: ['d17', 'd27', 'd30', 'd7', 'd13'],
      checklistIds: ['c6', 'c10', 'c26', 'c30', 'c15'],
      discussionCount: 5,
      attachmentCount: 5,
    ),
    ProjectTask(
      id: 't13',
      title: 'Performance Optimization',
      description:
          'Optimize application performance. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.\nSed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?',
      priority: 'low',
      status: 'awaitFeedback',
      startDate: DateTime(2025, 1, 2),
      dueDate: DateTime(2025, 2, 25),
      assignedMemberIds: ['m4'],
      tags: ['Performance', 'Optimization', 'Backend'],
      attachmentIds: ['a14', 'a30', 'a15', 'a17', 'a8'],
      activityIds: ['act6', 'act13', 'act20', 'act27', 'act4'],
      discussionIds: ['d5', 'd15', 'd25', 'd30', 'd13'],
      checklistIds: ['c15', 'c17', 'c19', 'c23', 'c30'],
      discussionCount: 5,
      attachmentCount: 5,
    ),
    ProjectTask(
      id: 't14',
      title: 'User Role Management',
      description:
          'Implement user roles and permissions. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.\nSed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?',
      priority: 'medium',
      status: 'completed',
      startDate: DateTime(2025, 1, 13),
      dueDate: DateTime(2025, 2, 25),
      assignedMemberIds: ['m1', 'm7'],
      tags: ['Security', 'Roles', 'Backend'],
      attachmentIds: ['a15', 'a20', 'a21', 'a28', 'a11'],
      activityIds: ['act7', 'act14', 'act21', 'act28', 'act5'],
      discussionIds: ['d15', 'd20', 'd25', 'd30', 'd10'],
      checklistIds: ['c19', 'c20', 'c21', 'c29', 'c7'],
      discussionCount: 5,
      attachmentCount: 5,
    ),
    ProjectTask(
      id: 't15',
      title: 'Implement Notifications System',
      description:
          'Develop real-time notifications for user activities. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.\nSed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?',
      priority: 'medium',
      status: 'testing',
      startDate: DateTime(2025, 2, 1),
      dueDate: DateTime(2025, 3, 10),
      assignedMemberIds: ['m4'],
      tags: ['Notifications', 'Real-time', 'Backend'],
      attachmentIds: ['a16', 'a29', 'a9', 'a15', 'a4'],
      activityIds: ['act8', 'act15', 'act22', 'act29', 'act6'],
      discussionIds: ['d16', 'd25', 'd28', 'd13', 'd3'],
      checklistIds: ['c15', 'c16', 'c23', 'c27', 'c10'],
      discussionCount: 5,
      attachmentCount: 5,
    ),
    ProjectTask(
      id: 't16',
      title: 'Create Admin Dashboard',
      description:
          'Build an administrative interface for managing the application. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.\nSed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?',
      priority: 'high',
      status: 'testing',
      startDate: DateTime(2025, 2, 15),
      dueDate: DateTime(2025, 4, 1),
      assignedMemberIds: ['m1', 'm3'],
      tags: ['Admin', 'Dashboard', 'UI'],
      attachmentIds: ['a17', 'a24', 'a6', 'a15', 'a21'],
      activityIds: ['act9', 'act16', 'act23', 'act30', 'act7'],
      discussionIds: ['d17', 'd21', 'd25', 'd30', 'd14'],
      checklistIds: ['c19', 'c13', 'c23', 'c24', 'c5'],
      discussionCount: 5,
      attachmentCount: 5,
    ),
    ProjectTask(
      id: 't17',
      title: 'Implement Search Functionality',
      description:
          'Add a global search feature to the application. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.\nSed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?',
      priority: 'medium',
      status: 'awaitFeedback',
      startDate: DateTime(2025, 3, 1),
      dueDate: DateTime(2025, 3, 25),
      assignedMemberIds: ['m2', 'm4'],
      tags: ['Search', 'Functionality', 'Frontend'],
      attachmentIds: ['a26', 'a22', 'a4', 'a13', 'a28', 'a31'],
      activityIds: ['act1', 'act11', 'act21', 'act5', 'act15', 'act31'],
      discussionIds: ['d7', 'd17', 'd27', 'd3', 'd13', 'd31', 'd41'],
      checklistIds: ['c6', 'c5', 'c12', 'c28', 'c30'],
      discussionCount: 7,
      attachmentCount: 6,
    ),
    ProjectTask(
      id: 't18',
      title: 'Accessibility Improvements',
      description:
          'Improve the application to meet accessibility standards (WCAG). Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.\nSed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?',
      priority: 'low',
      status: 'inProgress',
      startDate: DateTime(2025, 3, 15),
      dueDate: DateTime(2025, 4, 15),
      assignedMemberIds: ['m3'],
      tags: ['Accessibility', 'UI'],
      attachmentIds: ['a18', 'a25', 'a1', 'a6', 'a11', 'a32', 'a33', 'a34'],
      activityIds: ['act2', 'act12', 'act22', 'act6', 'act16', 'act32'],
      discussionIds: ['d8', 'd18', 'd28', 'd4', 'd14', 'd32', 'd42', 'd52'],
      checklistIds: ['c18', 'c1', 'c2', 'c3', 'c21'],
      discussionCount: 8,
      attachmentCount: 8,
    ),
    ProjectTask(
      id: 't19',
      title: 'Implement Two-Factor Authentication',
      description:
          'Enhance security by adding two-factor authentication. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.\nSed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?',
      priority: 'high',
      status: 'notStarted',
      startDate: DateTime(2025, 4, 1),
      dueDate: DateTime(2025, 4, 20),
      assignedMemberIds: ['m1', 'm4'],
      tags: ['Security', 'Authentication', 'Backend'],
      attachmentIds: ['a19', 'a30', 'a8', 'a15', 'a21', 'a35', 'a36'],
      activityIds: ['act3', 'act13', 'act23', 'act7', 'act17', 'act33'],
      discussionIds: ['d9', 'd19', 'd29', 'd5', 'd15', 'd33'],
      checklistIds: ['c19', 'c7', 'c10', 'c20', 'c30'],
      discussionCount: 6,
      attachmentCount: 7,
    ),
    ProjectTask(
      id: 't20',
      title: 'Create Data Export Feature',
      description:
          'Allow users to export their data in various formats (CSV, JSON). Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.\nSed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?',
      priority: 'medium',
      status: 'inProgress',
      startDate: DateTime(2025, 4, 15),
      dueDate: DateTime(2025, 5, 10),
      assignedMemberIds: ['m2', 'm3'],
      tags: ['Data', 'Export', 'Frontend'],
      attachmentIds: ['a20', 'a21', 'a4', 'a9', 'a11', 'a37'],
      activityIds: ['act4', 'act14', 'act24', 'act8', 'act18', 'act34'],
      discussionIds: ['d10', 'd20', 'd30', 'd6', 'd16', 'd34', 'd44'],
      checklistIds: ['c20', 'c7', 'c8', 'c12', 'c23'],
      discussionCount: 7,
      attachmentCount: 6,
    ),
    ProjectTask(
      id: 't21',
      title: 'Update Dependencies',
      description:
          'Update all project dependencies to their latest stable versions. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.\nSed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?',
      priority: 'low',
      status: 'notStarted',
      startDate: DateTime(2025, 5, 1),
      dueDate: DateTime(2025, 5, 15),
      assignedMemberIds: ['m1', 'm4'],
      tags: ['Maintenance', 'Dependencies'],
      attachmentIds: ['a21', 'a25', 'a19', 'a10', 'a13', 'a38', 'a39', 'a40'],
      activityIds: ['act5', 'act15', 'act25', 'act9', 'act19', 'act35'],
      discussionIds: ['d11', 'd21', 'd1', 'd7', 'd17', 'd35', 'd45', 'd55'],
      checklistIds: ['c21', 'c29', 'c1', 'c2', 'c3'],
      discussionCount: 8,
      attachmentCount: 8,
    ),
    ProjectTask(
      id: 't22',
      title: 'Implement Password Reset',
      description:
          'Allow users to reset their forgotten passwords. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.\nSed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?',
      priority: 'high',
      status: 'notStarted',
      startDate: DateTime(2025, 5, 10),
      dueDate: DateTime(2025, 5, 30),
      assignedMemberIds: ['m5', 'm2'],
      tags: ['Authentication', 'Security', 'Backend'],
      attachmentIds: ['a22', 'a14', 'a12', 'a3', 'a6', 'a41'],
      activityIds: ['act6', 'act16', 'act26', 'act10', 'act20', 'act36'],
      discussionIds: ['d12', 'd22', 'd2', 'd8', 'd18', 'd36'],
      checklistIds: ['c22', 'c3', 'c12', 'c28', 'c14'],
      discussionCount: 6,
      attachmentCount: 6,
    ),
    ProjectTask(
      id: 't23',
      title: 'Develop Usage Analytics',
      description:
          'Implement tracking of key user actions for analytics purposes. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.\nSed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?',
      priority: 'medium',
      status: 'testing',
      startDate: DateTime(2025, 5, 20),
      dueDate: DateTime(2025, 6, 15),
      assignedMemberIds: ['m9'],
      tags: ['Analytics', 'Tracking', 'Backend'],
      attachmentIds: ['a23', 'a30', 'a18', 'a11', 'a4', 'a42', 'a43'],
      activityIds: ['act7', 'act17', 'act27', 'act11', 'act21', 'act37'],
      discussionIds: ['d13', 'd23', 'd3', 'd9', 'd19', 'd37', 'd47'],
      checklistIds: ['c23', 'c7', 'c17', 'c10', 'c24'],
      discussionCount: 7,
      attachmentCount: 7,
    ),
    ProjectTask(
      id: 't24',
      title: 'Create Help Documentation',
      description:
          'Write user manuals and API documentation. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.\nSed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?',
      priority: 'low',
      status: 'inProgress',
      startDate: DateTime(2025, 6, 1),
      dueDate: DateTime(2025, 6, 30),
      assignedMemberIds: ['m1', 'm8'],
      tags: ['Documentation', 'Help'],
      attachmentIds: ['a24', 'a21', 'a5', 'a4', 'a13', 'a44', 'a45', 'a46'],
      activityIds: ['act8', 'act18', 'act28', 'act12', 'act22', 'act38'],
      discussionIds: ['d14', 'd24', 'd4', 'd10', 'd20', 'd38', 'd48', 'd58'],
      checklistIds: ['c24', 'c23', 'c19', 'c7', 'c15'],
      discussionCount: 8,
      attachmentCount: 8,
    ),
    ProjectTask(
      id: 't25',
      title: 'Implement Image Upload',
      description:
          'Allow users to upload images to their profiles. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.\nSed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?',
      priority: 'medium',
      status: 'completed',
      startDate: DateTime(2025, 6, 10),
      dueDate: DateTime(2025, 7, 5),
      assignedMemberIds: ['m9'],
      tags: ['File Upload', 'UI', 'Backend'],
      attachmentIds: ['a25', 'a3', 'a1', 'a10', 'a17', 'a47'],
      activityIds: ['act9', 'act19', 'act29', 'act13', 'act23', 'act39'],
      discussionIds: ['d15', 'd25', 'd5', 'd11', 'd21', 'd39'],
      checklistIds: ['c25', 'c1', 'c2', 'c3', 'c13'],
      discussionCount: 6,
      attachmentCount: 6,
    ),
    ProjectTask(
      id: 't26',
      title: 'Refactor Codebase',
      description:
          'Improve code readability and maintainability through refactoring. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.\nSed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?',
      priority: 'medium',
      status: 'completed',
      startDate: DateTime(2025, 7, 1),
      dueDate: DateTime(2025, 7, 20),
      assignedMemberIds: ['m9', 'm4'],
      tags: ['Refactoring', 'Maintenance'],
      attachmentIds: ['a26', 'a16', 'a4', 'a10', 'a27', 'a48', 'a49'],
      activityIds: ['act10', 'act20', 'act30', 'act14', 'act24', 'act40'],
      discussionIds: ['d16', 'd26', 'd6', 'd12', 'd22', 'd40', 'd50'],
      checklistIds: ['c26', 'c15', 'c16', 'c30', 'c9'],
      discussionCount: 7,
      attachmentCount: 7,
    ),
    ProjectTask(
      id: 't27',
      title: 'Implement Chat Feature',
      description:
          'Add a real-time chat functionality for users. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.\nSed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?',
      priority: 'high',
      status: 'completed',
      startDate: DateTime(2025, 7, 15),
      dueDate: DateTime(2025, 8, 15),
      assignedMemberIds: ['m9', 'm4'],
      tags: ['Chat', 'Real-time', 'Frontend'],
      attachmentIds: ['a27', 'a24', 'a1', 'a14', 'a19', 'a50', 'a51', 'a52'],
      activityIds: ['act11', 'act21', 'act1', 'act15', 'act25', 'act41'],
      discussionIds: ['d17', 'd27', 'd7', 'd13', 'd23', 'd41', 'd51', 'd61'],
      checklistIds: ['c27', 'c24', 'c23', 'c29', 'c5'],
      discussionCount: 8,
      attachmentCount: 8,
    ),
    ProjectTask(
      id: 't28',
      title: 'Optimize Database Queries',
      description:
          'Analyze and optimize slow-performing database queries. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.\nSed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?',
      priority: 'medium',
      status: 'testing',
      startDate: DateTime(2025, 8, 1),
      dueDate: DateTime(2025, 8, 20),
      assignedMemberIds: ['m4'],
      tags: ['Database', 'Optimization', 'Backend'],
      attachmentIds: ['a28', 'a12', 'a4', 'a22', 'a30', 'a53'],
      activityIds: ['act12', 'act22', 'act2', 'act16', 'act26', 'act42'],
      discussionIds: ['d18', 'd28', 'd8', 'd14', 'd24', 'd42'],
      checklistIds: ['c28', 'c12', 'c11', 'c30', 'c6'],
      discussionCount: 6,
      attachmentCount: 6,
    ),
    ProjectTask(
      id: 't29',
      title: 'Implement Localization',
      description:
          'Add support for multiple languages. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.\nSed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?',
      priority: 'low',
      status: 'testing',
      startDate: DateTime(2025, 8, 15),
      dueDate: DateTime(2025, 9, 10),
      assignedMemberIds: ['m3'],
      tags: ['Localization', 'Internationalization'],
      attachmentIds: ['a29', 'a16', 'a17', 'a3', 'a1', 'a54', 'a55'],
      activityIds: ['act13', 'act23', 'act3', 'act17', 'act27', 'act43'],
      discussionIds: ['d19', 'd29', 'd9', 'd15', 'd25', 'd43', 'd53'],
      checklistIds: ['c16', 'c1', 'c2', 'c13', 'c3'],
      discussionCount: 7,
      attachmentCount: 7,
    ),
    ProjectTask(
      id: 't30',
      title: 'Implement Background Jobs',
      description:
          'Set up background processing for tasks like email sending. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.\nSed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?',
      priority: 'medium',
      status: 'inProgress',
      startDate: DateTime(2025, 9, 1),
      dueDate: DateTime(2025, 9, 20),
      assignedMemberIds: ['m4'],
      tags: ['Background Jobs', 'Backend'],
      attachmentIds: ['a30', 'a25', 'a19', 'a14', 'a13', 'a56', 'a57', 'a58'],
      activityIds: ['act14', 'act24', 'act4', 'act18', 'act28', 'act44'],
      discussionIds: ['d20', 'd30', 'd10', 'd16', 'd26', 'd44', 'd54', 'd64'],
      checklistIds: ['c30', 'c21', 'c29', 'c28', 'c6'],
      discussionCount: 8,
      attachmentCount: 8,
    ),
  ],
  attachments: [
    ProjectAttachment(
      id: 'a1',
      name: 'How to build a website with Flutter Vibe Codding',
      url: 'https://example.com/files/build_flutter_web_vide_codding.pdf',
      fileType: 'pdf',
      fileSize: 3518,
      uploadedAt: DateTime(2024, 11, 28, 10, 30),
    ),
    ProjectAttachment(
      id: 'a2',
      name: 'Flutter State Management Guide',
      url: 'https://example.com/files/flutter_state_management_guide.docx',
      fileType: 'docx',
      fileSize: 1231,
      uploadedAt: DateTime(2024, 12, 2, 09, 15),
    ),
    ProjectAttachment(
      id: 'a3',
      name: 'UI Design Mockups - Login Screen',
      url: 'https://example.com/files/login_screen_mockups.pptx',
      fileType: 'pptx',
      fileSize: 2048,
      uploadedAt: DateTime(2024, 12, 5, 14, 45),
    ),
    ProjectAttachment(
      id: 'a4',
      name: 'API Endpoints Documentation v1.0',
      url: 'https://example.com/files/api_docs_v1.0.zip',
      fileType: 'zip',
      fileSize: 567,
      uploadedAt: DateTime(2024, 12, 10, 11, 20),
    ),
    ProjectAttachment(
      id: 'a5',
      name: 'Unit Test Cases - Authentication',
      url: 'https://example.com/files/unit_tests_auth.xlsx',
      fileType: 'xlsx',
      fileSize: 890,
      uploadedAt: DateTime(2024, 12, 15, 16, 05),
    ),
    ProjectAttachment(
      id: 'a6',
      name: 'User Profile Page Wireframes',
      url: 'https://example.com/files/user_profile_wireframes.pdf',
      fileType: 'pdf',
      fileSize: 1876,
      uploadedAt: DateTime(2024, 12, 20, 13, 10),
    ),
    ProjectAttachment(
      id: 'a7',
      name: 'Settings Screen Design Specs',
      url: 'https://example.com/files/settings_design_specs.pdf',
      fileType: 'pdf',
      fileSize: 312,
      uploadedAt: DateTime(2024, 12, 25, 08, 50),
    ),
    ProjectAttachment(
      id: 'a8',
      name: 'Database Schema Diagram',
      url: 'https://example.com/files/database_schema.docx',
      fileType: 'docx',
      fileSize: 1450,
      uploadedAt: DateTime(2024, 12, 30, 15, 30),
    ),
    ProjectAttachment(
      id: 'a9',
      name: 'Backend API Development Plan',
      url: 'https://example.com/files/backend_plan.docx',
      fileType: 'docx',
      fileSize: 921,
      uploadedAt: DateTime(2025, 1, 5, 10, 00),
    ),
    ProjectAttachment(
      id: 'a10',
      name: 'User Onboarding Flow Diagram',
      url: 'https://example.com/files/onboarding_flow.pdf',
      fileType: 'pdf',
      fileSize: 678,
      uploadedAt: DateTime(2025, 1, 10, 11, 40),
    ),
    ProjectAttachment(
      id: 'a11',
      name: 'Data Validation Rules',
      url: 'https://example.com/files/data_validation_rules.docx',
      fileType: 'docx',
      fileSize: 234,
      uploadedAt: DateTime(2025, 1, 15, 09, 25),
    ),
    ProjectAttachment(
      id: 'a12',
      name: 'Integration Test Scenarios',
      url: 'https://example.com/files/integration_tests.pptx',
      fileType: 'pptx',
      fileSize: 1122,
      uploadedAt: DateTime(2025, 1, 20, 14, 15),
    ),
    ProjectAttachment(
      id: 'a13',
      name: 'Staging Deployment Checklist',
      url: 'https://example.com/files/staging_checklist.pdf',
      fileType: 'pdf',
      fileSize: 789,
      uploadedAt: DateTime(2025, 1, 25, 17, 00),
    ),
    ProjectAttachment(
      id: 'a14',
      name: 'Performance Optimization Report',
      url: 'https://example.com/files/performance_report.pdf',
      fileType: 'pdf',
      fileSize: 2876,
      uploadedAt: DateTime(2025, 1, 30, 11, 10),
    ),
    ProjectAttachment(
      id: 'a15',
      name: 'User Role Management Specification',
      url: 'https://example.com/files/user_roles_spec.docx',
      fileType: 'docx',
      fileSize: 1543,
      uploadedAt: DateTime(2025, 2, 5, 10, 45),
    ),
    ProjectAttachment(
      id: 'a16',
      name: 'Notifications System Design',
      url: 'https://example.com/files/notifications_design.pdf',
      fileType: 'pdf',
      fileSize: 456,
      uploadedAt: DateTime(2025, 2, 10, 13, 20),
    ),
    ProjectAttachment(
      id: 'a17',
      name: 'Admin Dashboard Mockups',
      url: 'https://example.com/files/admin_dashboard_mockups.pptx',
      fileType: 'pptx',
      fileSize: 2319,
      uploadedAt: DateTime(2025, 2, 15, 15, 55),
    ),
    ProjectAttachment(
      id: 'a18',
      name: 'Search Functionality Implementation Guide',
      url: 'https://example.com/files/search_guide.pptx',
      fileType: 'pptx',
      fileSize: 1345,
      uploadedAt: DateTime(2025, 2, 20, 09, 30),
    ),
    ProjectAttachment(
      id: 'a19',
      name: 'Accessibility Audit Report',
      url: 'https://example.com/files/accessibility_report.pdf',
      fileType: 'pdf',
      fileSize: 3102,
      uploadedAt: DateTime(2025, 2, 25, 11, 05),
    ),
    ProjectAttachment(
      id: 'a20',
      name: 'Two-Factor Authentication Flow',
      url: 'https://example.com/files/two_fa_flow.docx',
      fileType: 'docx',
      fileSize: 1678,
      uploadedAt: DateTime(2025, 3, 2, 14, 40),
    ),
    ProjectAttachment(
      id: 'a21',
      name: 'Data Export Formats Specification',
      url: 'https://example.com/files/data_export_spec.docx',
      fileType: 'docx',
      fileSize: 1011,
      uploadedAt: DateTime(2025, 3, 7, 10, 15),
    ),
    ProjectAttachment(
      id: 'a22',
      name: 'Dependencies Update Plan',
      url: 'https://example.com/files/dependencies_plan.xlsx',
      fileType: 'xlsx',
      fileSize: 765,
      uploadedAt: DateTime(2025, 3, 12, 16, 20),
    ),
    ProjectAttachment(
      id: 'a23',
      name: 'Password Reset Implementation Details',
      url: 'https://example.com/files/password_reset_details.docx',
      fileType: 'docx',
      fileSize: 389,
      uploadedAt: DateTime(2025, 3, 17, 09, 05),
    ),
    ProjectAttachment(
      id: 'a24',
      name: 'Usage Analytics Dashboard Design',
      url: 'https://example.com/files/analytics_dashboard.pdf',
      fileType: 'pdf',
      fileSize: 512,
      uploadedAt: DateTime(2025, 3, 22, 13, 50),
    ),
    ProjectAttachment(
      id: 'a25',
      name: 'User Manual v1.0',
      url: 'https://example.com/files/user_manual_v1.0.pdf',
      fileType: 'pdf',
      fileSize: 4210,
      uploadedAt: DateTime(2025, 3, 27, 15, 10),
    ),
    ProjectAttachment(
      id: 'a26',
      name: 'API Documentation v1.1',
      url: 'https://example.com/files/api_docs_v1.1.zip',
      fileType: 'zip',
      fileSize: 621,
      uploadedAt: DateTime(2025, 4, 1, 10, 30),
    ),
    ProjectAttachment(
      id: 'a27',
      name: 'Image Upload Integration Guide',
      url: 'https://example.com/files/image_upload_guide.pptx',
      fileType: 'pptx',
      fileSize: 1488,
      uploadedAt: DateTime(2025, 4, 6, 11, 45),
    ),
    ProjectAttachment(
      id: 'a28',
      name: 'Code Refactoring Plan',
      url: 'https://example.com/files/refactoring_plan.docx',
      fileType: 'docx',
      fileSize: 1155,
      uploadedAt: DateTime(2025, 4, 11, 14, 00),
    ),
    ProjectAttachment(
      id: 'a29',
      name: 'Chat Feature UI/UX Design',
      url: 'https://example.com/files/chat_design.pptx',
      fileType: 'pptx',
      fileSize: 2567,
      uploadedAt: DateTime(2025, 4, 16, 16, 30),
    ),
    ProjectAttachment(
      id: 'a30',
      name: 'Database Query Optimization Notes',
      url: 'https://example.com/files/query_optimization.docx',
      fileType: 'docx',
      fileSize: 412,
      uploadedAt: DateTime(2025, 4, 21, 09, 55),
    ),
  ],
  activities: [
    ProjectActivity(
      id: 'act1',
      type: 'checklist',
      description: 'Bob added a checklist to task "Create Login Screen".',
      memberId: 'm2',
      timestamp: DateTime(2024, 12, 3, 10, 30),
    ),
    ProjectActivity(
      id: 'act2',
      type: 'status_change',
      description: 'Milestone "Project Setup" marked as completedd.',
      memberId: 'm1',
      timestamp: DateTime(2024, 12, 10, 9, 0),
    ),
    ProjectActivity(
      id: 'act3',
      type: 'file_upload',
      description: 'Charlie uploaded system-requirement.pdf.',
      memberId: 'm3',
      timestamp: DateTime(2024, 12, 2, 14, 45),

      attachmentUrl: 'https://example.com/files/system-requirement.pdf',
    ),
    ProjectActivity(
      id: 'act4',
      type: 'task_assignment',
      description:
          'Umar assigned "Implement API Integration" to Bob and Diana.',
      memberId: 'm1',
      timestamp: DateTime(2024, 12, 11, 11, 0),
    ),
    ProjectActivity(
      id: 'act5',
      type: 'checklist',
      description: 'Diana added checklist on "Backend Development" progress.',
      memberId: 'm4',
      timestamp: DateTime(2024, 12, 18, 16, 20),
    ),
    ProjectActivity(
      id: 'act6',
      type: 'status_change',
      description: 'Task "Design Dashboard UI" status changed to "completed".',
      memberId: 'm3',
      timestamp: DateTime(2024, 12, 5, 17, 0),
    ),
    ProjectActivity(
      id: 'act7',
      type: 'file_upload',
      description: 'Bob uploaded login-flow-diagram.png.',
      memberId: 'm2',
      timestamp: DateTime(2024, 12, 14, 9, 15),

      attachmentUrl: 'https://example.com/files/login-flow-diagram.png',
    ),
    ProjectActivity(
      id: 'act8',
      type: 'task_update',
      description: 'Umar updated the due date for "Write Unit Tests".',
      memberId: 'm1',
      timestamp: DateTime(2024, 12, 20, 10, 0),
    ),
    ProjectActivity(
      id: 'act9',
      type: 'checklist',
      description: 'Charlie add checklist on "User Profile Page".',
      memberId: 'm3',
      timestamp: DateTime(2024, 12, 22, 14, 0),
    ),
    ProjectActivity(
      id: 'act10',
      type: 'status_change',
      description:
          'Task "Database Schema Design" status changed to "completed".',
      memberId: 'm1',
      timestamp: DateTime(2024, 11, 10, 16, 30),
    ),
    ProjectActivity(
      id: 'act11',
      type: 'file_upload',
      description: 'Diana uploaded backend-api-spec.json.',
      memberId: 'm4',
      timestamp: DateTime(2024, 12, 15, 11, 40),

      attachmentUrl: 'https://example.com/files/backend-api-spec.json',
    ),
    ProjectActivity(
      id: 'act12',
      type: 'task_assignment',
      description: 'Umar assigned "Create Onboarding Flow" to Charlie.',
      memberId: 'm1',
      timestamp: DateTime(2024, 12, 1, 10, 0),
    ),
    ProjectActivity(
      id: 'act13',
      type: 'checklist',
      description:
          'Bob added checklist on clarification on data validation rules.',
      memberId: 'm2',
      timestamp: DateTime(2024, 12, 10, 13, 0),
    ),
    ProjectActivity(
      id: 'act14',
      type: 'status_change',
      description:
          'Task "Implement API Integration" status changed to "inProgress".',
      memberId: 'm2',
      timestamp: DateTime(2024, 12, 13, 9, 0),
    ),
    ProjectActivity(
      id: 'act15',
      type: 'file_upload',
      description: 'Umar uploaded project-roadmap-2025.pdf.',
      memberId: 'm1',
      timestamp: DateTime(2025, 1, 5, 10, 0),

      attachmentUrl: 'https://example.com/files/project-roadmap-2025.pdf',
    ),
    ProjectActivity(
      id: 'act16',
      type: 'task_completion',
      description: 'Bob completed task "Create Login Screen".',
      memberId: 'm2',
      timestamp: DateTime(2024, 12, 16, 17, 30),
    ),
    ProjectActivity(
      id: 'act17',
      type: 'checklist',
      description: 'Diana added checklist on "Performance Optimization".',
      memberId: 'm4',
      timestamp: DateTime(2025, 1, 3, 11, 0),
    ),
    ProjectActivity(
      id: 'act18',
      type: 'task_update',
      description:
          'Umar adjusted priority of "Implement Settings Screen" to high.',
      memberId: 'm1',
      timestamp: DateTime(2025, 1, 1, 14, 0),
    ),
    ProjectActivity(
      id: 'act19',
      type: 'file_upload',
      description: 'Charlie uploaded onboarding-screens-v2.fig.',
      memberId: 'm3',
      timestamp: DateTime(2025, 1, 12, 15, 0),

      attachmentUrl: 'https://example.com/files/onboarding-screens-v2.fig',
    ),
    ProjectActivity(
      id: 'act20',
      type: 'status_change',
      description: 'Task "Write Unit Tests" status changed to "inProgress".',
      memberId: 'm2',
      timestamp: DateTime(2024, 11, 20, 10, 0),
    ),
    ProjectActivity(
      id: 'act21',
      type: 'checklist',
      description: 'Bob added checklist on integration test cases for API.',
      memberId: 'm2',
      timestamp: DateTime(2025, 1, 2, 16, 0),
    ),
  ],
  discussions: [
    ProjectDiscussion(
      id: 'd1',
      taskId: 't1',
      memberId: 'm2',
      message: 'Login UI is mostly done, waiting for validation rules.',
      createdAt: DateTime(2024, 12, 3, 10, 15),
    ),
    ProjectDiscussion(
      id: 'd2',
      taskId: 't1',
      memberId: 'm1',
      message: 'Please follow the design specs from Figma.',
      createdAt: DateTime(2024, 12, 3, 11, 00),
      parentDiscussionId: 'd1',
    ),
    ProjectDiscussion(
      id: 'd3',
      taskId: 't3',
      memberId: 'm4',
      message: 'Auth API is ready on staging.',
      createdAt: DateTime(2024, 12, 12, 14, 30),
      attachmentIds: ['a9'],
    ),
    ProjectDiscussion(
      id: 'd4',
      taskId: 't5',
      memberId: 'm3',
      message: 'User profile layout needs UX review.',
      createdAt: DateTime(2024, 12, 22, 13, 45),
    ),
    ProjectDiscussion(
      id: 'd5',
      taskId: 't8',
      memberId: 'm7',
      message: 'Backend performance looks stable after refactor.',
      createdAt: DateTime(2025, 1, 8, 16, 10),
    ),
    ProjectDiscussion(
      id: 'd6',
      taskId: 't6',
      memberId: 'm5',
      message: 'Unit tests for payment gateway are passing.',
      createdAt: DateTime(2025, 1, 10, 09, 20),
    ),
    ProjectDiscussion(
      id: 'd7',
      taskId: 't7',
      memberId: 'm6',
      message: 'Updated the README with deployment steps.',
      createdAt: DateTime(2025, 1, 12, 11, 45),
    ),
    ProjectDiscussion(
      id: 'd8',
      taskId: 't9',
      memberId: 'm8',
      message: 'New icons uploaded to the assets folder.',
      createdAt: DateTime(2025, 1, 15, 14, 05),
      attachmentIds: ['a10'],
    ),
    ProjectDiscussion(
      id: 'd9',
      taskId: 't10',
      memberId: 'm9',
      message: 'Database migration for user preferences is complete.',
      createdAt: DateTime(2025, 1, 18, 10, 30),
    ),
    ProjectDiscussion(
      id: 'd10',
      taskId: 't11',
      memberId: 'm10',
      message: 'Starting the integration for Third-party OAuth.',
      createdAt: DateTime(2025, 1, 20, 16, 50),
    ),
    ProjectDiscussion(
      id: 'd11',
      taskId: 't12',
      memberId: 'm2',
      message: 'Mobile responsive issues on the dashboard fixed.',
      createdAt: DateTime(2025, 1, 22, 13, 15),
    ),
    ProjectDiscussion(
      id: 'd12',
      taskId: 't12',
      memberId: 'm1',
      message: 'Can you check the sidebar on iPhone SE?',
      createdAt: DateTime(2025, 1, 22, 14, 00),
      parentDiscussionId: 'd11',
    ),
    ProjectDiscussion(
      id: 'd13',
      taskId: 't13',
      memberId: 'm4',
      message: 'Caching layer implemented for the product list.',
      createdAt: DateTime(2025, 1, 25, 08, 45),
    ),
    ProjectDiscussion(
      id: 'd14',
      taskId: 't14',
      memberId: 'm3',
      message: 'Color palette updated to follow the new brand guidelines.',
      createdAt: DateTime(2025, 1, 28, 11, 20),
    ),
    ProjectDiscussion(
      id: 'd15',
      taskId: 't15',
      memberId: 'm7',
      message: 'Query optimization reduced load time by 40%.',
      createdAt: DateTime(2025, 2, 1, 15, 30),
    ),
    ProjectDiscussion(
      id: 'd16',
      taskId: 't16',
      memberId: 'm5',
      message: 'CI/CD pipeline is failing on the build step.',
      createdAt: DateTime(2025, 2, 3, 09, 10),
    ),
    ProjectDiscussion(
      id: 'd17',
      taskId: 't17',
      memberId: 'm6',
      message: 'Documentation for API v2 is now live.',
      createdAt: DateTime(2025, 2, 5, 10, 00),
      attachmentIds: ['a11'],
    ),
    ProjectDiscussion(
      id: 'd18',
      taskId: 't18',
      memberId: 'm8',
      message: 'Dark mode toggle is now functional.',
      createdAt: DateTime(2025, 2, 7, 17, 45),
    ),
    ProjectDiscussion(
      id: 'd19',
      taskId: 't19',
      memberId: 'm9',
      message:
          'Bug found in search filters when selecting multiple categories.',
      createdAt: DateTime(2025, 2, 10, 12, 20),
    ),
    ProjectDiscussion(
      id: 'd20',
      taskId: 't20',
      memberId: 'm10',
      message: 'Security patch applied to prevent SQL injection.',
      createdAt: DateTime(2025, 2, 12, 14, 15),
    ),
    ProjectDiscussion(
      id: 'd21',
      taskId: 't21',
      memberId: 'm2',
      message: 'New landing page animation is ready for review.',
      createdAt: DateTime(2025, 2, 14, 11, 05),
    ),
    ProjectDiscussion(
      id: 'd22',
      taskId: 't22',
      memberId: 'm4',
      message: 'Export to CSV feature added to reports.',
      createdAt: DateTime(2025, 2, 16, 16, 40),
    ),
    ProjectDiscussion(
      id: 'd23',
      taskId: 't23',
      memberId: 'm1',
      message: 'Logo needs to be slightly larger in the header.',
      createdAt: DateTime(2025, 2, 18, 09, 50),
    ),
    ProjectDiscussion(
      id: 'd24',
      taskId: 't24',
      memberId: 'm3',
      message: 'Font sizes adjusted for accessibility (WCAG 2.1).',
      createdAt: DateTime(2025, 2, 20, 15, 10),
    ),
    ProjectDiscussion(
      id: 'd25',
      taskId: 't25',
      memberId: 'm7',
      message: 'Redis setup finished for session management.',
      createdAt: DateTime(2025, 2, 22, 10, 30),
    ),
    ProjectDiscussion(
      id: 'd26',
      taskId: 't26',
      memberId: 'm5',
      message: 'Password reset flow tested and verified.',
      createdAt: DateTime(2025, 2, 24, 14, 00),
    ),
    ProjectDiscussion(
      id: 'd27',
      taskId: 't27',
      memberId: 'm6',
      message: 'Terms of Service updated in the footer.',
      createdAt: DateTime(2025, 2, 26, 11, 25),
    ),
    ProjectDiscussion(
      id: 'd28',
      taskId: 't28',
      memberId: 'm8',
      message: 'Email notification template revamped.',
      createdAt: DateTime(2025, 2, 28, 13, 55),
      attachmentIds: ['a12'],
    ),
    ProjectDiscussion(
      id: 'd29',
      taskId: 't29',
      memberId: 'm9',
      message: 'Handling of large file uploads improved.',
      createdAt: DateTime(2025, 3, 2, 10, 10),
    ),
    ProjectDiscussion(
      id: 'd30',
      taskId: 't30',
      memberId: 'm10',
      message: 'Final QA before the sprint release starts tomorrow.',
      createdAt: DateTime(2025, 3, 4, 17, 30),
    ),
  ],
  checklists: [
    ProjectChecklistItem(id: 'c1', title: 'Create wireframe', isDone: true),
    ProjectChecklistItem(
      id: 'c2',
      title: 'Design color palette',
      isDone: false,
    ),
    ProjectChecklistItem(
      id: 'c3',
      title: 'Implement responsive layout',
      isDone: true,
    ),
    ProjectChecklistItem(id: 'c4', title: 'Dark mode support', isDone: false),

    ProjectChecklistItem(
      id: 'c5',
      title: 'Setup project repository',
      isDone: true,
    ),
    ProjectChecklistItem(
      id: 'c6',
      title: 'Configure CI/CD pipeline',
      isDone: false,
    ),
    ProjectChecklistItem(
      id: 'c7',
      title: 'Define database schema',
      isDone: false,
    ),
    ProjectChecklistItem(
      id: 'c8',
      title: 'Integrate Auth Provider',
      isDone: false,
    ),
    ProjectChecklistItem(id: 'c9', title: 'Create Login UI', isDone: true),
    ProjectChecklistItem(
      id: 'c10',
      title: 'Setup API documentation',
      isDone: false,
    ),
    ProjectChecklistItem(
      id: 'c11',
      title: 'Implement Forgot Password',
      isDone: true,
    ),
    ProjectChecklistItem(
      id: 'c12',
      title: 'Unit testing for Auth service',
      isDone: false,
    ),
    ProjectChecklistItem(
      id: 'c13',
      title: 'User Profile Dashboard',
      isDone: true,
    ),
    ProjectChecklistItem(
      id: 'c14',
      title: 'Image upload functionality',
      isDone: false,
    ),
    ProjectChecklistItem(
      id: 'c15',
      title: 'Notification system setup',
      isDone: true,
    ),
    ProjectChecklistItem(
      id: 'c16',
      title: 'Real-time chat integration',
      isDone: false,
    ),
    ProjectChecklistItem(
      id: 'c17',
      title: 'Optimization for SQL queries',
      isDone: true,
    ),
    ProjectChecklistItem(
      id: 'c18',
      title: 'Multi-language support (i18n)',
      isDone: false,
    ),
    ProjectChecklistItem(
      id: 'c19',
      title: 'Audit logs for admin panel',
      isDone: true,
    ),
    ProjectChecklistItem(
      id: 'c20',
      title: 'Payment gateway integration',
      isDone: false,
    ),
    ProjectChecklistItem(
      id: 'c21',
      title: 'Terms and Conditions page',
      isDone: true,
    ),
    ProjectChecklistItem(
      id: 'c22',
      title: 'Bug fixing for Safari browser',
      isDone: false,
    ),
    ProjectChecklistItem(
      id: 'c23',
      title: 'Search functionality with filters',
      isDone: false,
    ),
    ProjectChecklistItem(
      id: 'c24',
      title: 'CSV/PDF export feature',
      isDone: false,
    ),
    ProjectChecklistItem(
      id: 'c25',
      title: 'Mobile app splash screen',
      isDone: true,
    ),
    ProjectChecklistItem(
      id: 'c26',
      title: 'Deep linking configuration',
      isDone: false,
    ),
    ProjectChecklistItem(
      id: 'c27',
      title: 'Google Analytics integration',
      isDone: true,
    ),
    ProjectChecklistItem(
      id: 'c28',
      title: 'End-to-end testing with Cypress',
      isDone: false,
    ),
    ProjectChecklistItem(
      id: 'c29',
      title: 'Privacy Policy documentation',
      isDone: true,
    ),
    ProjectChecklistItem(
      id: 'c30',
      title: 'Final UAT with stakeholders',
      isDone: false,
    ),
  ],
);
