import 'package:flutkit_ademin/demo/page/team/team_models.dart';

List<UserProfile> dummyProfiles = [
  UserProfile(
    name: "Umar Hamzah",
    role: "Team Leader & HR",
    avatarUrl: 'assets/images/avatar_2.jpg',
    backgroundUrl: 'assets/images/bg_1.jpg',
    projects: 325,
    tasks: 147,
    isFavorite: true,
  ),
  UserProfile(
    name: "John Doe",
    role: "Software Engineer",
    avatarUrl: 'assets/images/avatar_3.jpg',
    backgroundUrl: 'assets/images/bg_2.jpg',
    projects: 150,
    tasks: 120,
    isFavorite: false,
  ),
  UserProfile(
    name: "Jane Smith",
    role: "Product Manager",
    avatarUrl: 'assets/images/avatar_4.jpg',
    backgroundUrl: 'assets/images/bg_3.jpg',
    projects: 300,
    tasks: 250,
    isFavorite: true,
  ),
  UserProfile(
    name: "Alice Johnson",
    role: "UI/UX Designer",
    avatarUrl: 'assets/images/avatar_5.jpg',
    backgroundUrl: 'assets/images/bg_4.jpg',
    projects: 180,
    tasks: 160,
    isFavorite: false,
  ),
  UserProfile(
    name: "Michael Brown",
    role: "Backend Developer",
    avatarUrl: 'assets/images/avatar_6.jpg',
    backgroundUrl: 'assets/images/bg_5.jpg',
    projects: 200,
    tasks: 180,
    isFavorite: true,
  ),
  UserProfile(
    name: "Emma Wilson",
    role: "QA Engineer",
    avatarUrl: 'assets/images/avatar_7.jpg',
    backgroundUrl: 'assets/images/bg_6.jpg',
    projects: 140,
    tasks: 130,
    isFavorite: false,
  ),
  UserProfile(
    name: "Liam Davis",
    role: "DevOps Engineer",
    avatarUrl: 'assets/images/avatar_8.jpg',
    backgroundUrl: 'assets/images/bg_7.jpg',
    projects: 220,
    tasks: 210,
    isFavorite: true,
  ),
  UserProfile(
    name: "Sophia Martinez",
    role: "Data Scientist",
    avatarUrl: 'assets/images/avatar_9.jpg',
    backgroundUrl: 'assets/images/bg_8.jpg',
    projects: 250,
    tasks: 240,
    isFavorite: false,
  ),
  UserProfile(
    name: "James Anderson",
    role: "Frontend Developer",
    avatarUrl: 'assets/images/avatar_10.jpg',
    backgroundUrl: 'assets/images/bg_9.jpg',
    projects: 190,
    tasks: 170,
    isFavorite: true,
  ),
  UserProfile(
    name: "Olivia Thomas",
    role: "Marketing Specialist",
    avatarUrl: 'assets/images/avatar_11.jpg',
    backgroundUrl: 'assets/images/bg_10.jpg',
    projects: 300,
    tasks: 280,
    isFavorite: false,
  ),
  UserProfile(
    name: "William Garcia",
    role: "Business Analyst",
    avatarUrl: 'assets/images/avatar_1.jpg',
    backgroundUrl: 'assets/images/bg_11.jpg',
    projects: 270,
    tasks: 260,
    isFavorite: true,
  ),
  UserProfile(
    name: "Isabella Rodriguez",
    role: "Content Writer",
    avatarUrl: 'assets/images/avatar_4.jpg',
    backgroundUrl: 'assets/images/bg_12.jpg',
    projects: 160,
    tasks: 150,
    isFavorite: false,
  ),
];
