import 'package:flutkit_ademin/demo/app/email/email_models.dart';

List<Email> buildDummyEmails() {
  return [
    // Inbox (5)
    Email(
      id: 'inbox_1',
      sender: 'alice1@example.com',
      senderName: 'Alice',
      recipient: ['you@example.com'],
      subject: 'Welcome Alice!',
      body:
          '''Dear User, Thank you for signing up for our service. We're excited to have you as part of our community.

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.


Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

Here are some of the benefits you'll enjoy:

Access to exclusive content
Personalized recommendations
24/7 customer support
To get started, please click the button below:

Activate Your Account

If you have any questions, feel free to contact us at support@example.com.''',
      timestamp: DateTime.now().subtract(const Duration(minutes: 30)),
      isRead: false,
      folder: EmailFolder.inbox,
      category: EmailCategory.updates,
    ),
    Email(
      id: 'inbox_2',
      sender: 'newsletter1@brand.com',
      senderName: 'BisDig',
      recipient: ['you@example.com'],
      subject: 'Today\'s Promotions',
      body:
          'Check out our latest deals on electronics, fashion, and more! This is the second email.',
      timestamp: DateTime.now().subtract(const Duration(hours: 2)),
      isRead: true,
      folder: EmailFolder.inbox,
      category: EmailCategory.promotions,
    ),
    Email(
      id: 'inbox_3',
      sender: 'bob1@community.org',
      senderName: 'RPM Forum',
      recipient: ['you@example.com'],
      cc: ['admin@community.org'],
      subject: 'Forum Thread Reply',
      body:
          'Thanks for your input on the topic. Your perspective was helpful. This is the third email.',
      timestamp: DateTime.now().subtract(const Duration(days: 1)),
      isRead: true,
      folder: EmailFolder.inbox,
      category: EmailCategory.forums,
    ),
    Email(
      id: 'inbox_4',
      sender: 'social1@network.com',
      senderName: 'Facebook',
      recipient: ['you@example.com'],
      subject: 'Friend Request',
      body:
          'You have a new friend request from John Doe. This is the fourth email.',
      timestamp: DateTime.now().subtract(const Duration(hours: 5)),
      isRead: false,
      folder: EmailFolder.inbox,
      category: EmailCategory.social,
    ),
    Email(
      id: 'inbox_5',
      sender: 'support1@company.com',
      senderName: 'Support Team',
      recipient: ['you@example.com'],
      subject: 'Your Support Ticket',
      body:
          'Your support ticket has been received and will be reviewed. This is the fifth email.',
      timestamp: DateTime.now().subtract(const Duration(hours: 12)),
      isRead: false,
      folder: EmailFolder.inbox,
    ),

    Email(
      id: 'inbox_6',
      sender: 'alice2@example.com',
      senderName: 'Alice',
      recipient: ['you@example.com'],
      subject: 'Welcome Again!',
      body:
          'Thanks for staying with our platform.\nWe’re still excited to have you onboard. This is the sixth email.',
      timestamp: DateTime.now().subtract(const Duration(minutes: 35)),
      isRead: false,
      folder: EmailFolder.inbox,
      category: EmailCategory.updates,
    ),
    Email(
      id: 'inbox_7',
      sender: 'newsletter2@brand.com',
      senderName: 'BisDig',
      recipient: ['you@example.com'],
      subject: 'More Promotions Today',
      body:
          'Check out our latest deals on electronics, fashion, and more! This is the seventh email.',
      timestamp: DateTime.now().subtract(const Duration(hours: 3)),
      isRead: true,
      folder: EmailFolder.inbox,
      category: EmailCategory.promotions,
    ),
    Email(
      id: 'inbox_8',
      sender: 'bob2@community.org',
      senderName: 'RPM Forum',
      recipient: ['you@example.com'],
      cc: ['admin@community.org'],
      subject: 'Another Forum Thread Reply',
      body:
          'Thanks again for your input on the topic. Your perspective continues to be helpful. This is the eighth email.',
      timestamp: DateTime.now().subtract(const Duration(days: 2)),
      isRead: true,
      folder: EmailFolder.inbox,
      category: EmailCategory.forums,
    ),
    Email(
      id: 'inbox_9',
      sender: 'social2@network.com',
      senderName: 'Facebook',
      recipient: ['you@example.com'],
      subject: 'Another Friend Request',
      body:
          'You have a new friend request from Jane Doe. This is the ninth email.',
      timestamp: DateTime.now().subtract(const Duration(hours: 6)),
      isRead: false,
      folder: EmailFolder.inbox,
      category: EmailCategory.social,
    ),
    Email(
      id: 'inbox_10',
      sender: 'support2@company.com',
      senderName: 'Support Team',
      recipient: ['you@example.com'],
      subject: 'Re: Your Support Ticket',
      body:
          'Your support ticket has been reviewed and we have a response. This is the tenth email.',
      timestamp: DateTime.now().subtract(const Duration(hours: 14)),
      isRead: false,
      folder: EmailFolder.inbox,
    ),

    Email(
      id: 'inbox_11',
      sender: 'alice3@example.com',
      senderName: 'Alice',
      recipient: ['you@example.com'],
      subject: 'Welcome back!',
      body:
          'Thanks for returning to our platform.\nWe’re always excited to have you onboard. This is the eleventh email.',
      timestamp: DateTime.now().subtract(const Duration(minutes: 40)),
      isRead: false,
      folder: EmailFolder.inbox,
      category: EmailCategory.updates,
    ),
    Email(
      id: 'inbox_12',
      sender: 'newsletter3@brand.com',
      senderName: 'BisDig',
      recipient: ['you@example.com'],
      subject: 'Even More Promotions Today',
      body:
          'Check out our latest deals on electronics, fashion, and more! This is the twelfth email.',
      timestamp: DateTime.now().subtract(const Duration(hours: 4)),
      isRead: true,
      folder: EmailFolder.inbox,
      category: EmailCategory.promotions,
    ),
    Email(
      id: 'inbox_13',
      sender: 'bob3@community.org',
      senderName: 'RPM Forum',
      recipient: ['you@example.com'],
      cc: ['admin@community.org'],
      subject: 'Yet Another Forum Thread Reply',
      body:
          'Thanks yet again for your input on the topic. Your perspective is invaluable. This is the thirteenth email.',
      timestamp: DateTime.now().subtract(const Duration(days: 3)),
      isRead: true,
      folder: EmailFolder.inbox,
      category: EmailCategory.forums,
    ),
    Email(
      id: 'inbox_14',
      sender: 'social3@network.com',
      senderName: 'Facebook',
      recipient: ['you@example.com'],
      subject: 'Another Another Friend Request',
      body:
          'You have a new friend request from Michael Smith. This is the fourteenth email.',
      timestamp: DateTime.now().subtract(const Duration(hours: 7)),
      isRead: false,
      folder: EmailFolder.inbox,
      category: EmailCategory.social,
    ),
    Email(
      id: 'inbox_15',
      sender: 'support3@company.com',
      senderName: 'Support Team',
      recipient: ['you@example.com'],
      subject: 'Final Response to Your Support Ticket',
      body:
          'This is the final response to your support ticket. We hope we have resolved your issue. This is the fifteenth email.',
      timestamp: DateTime.now().subtract(const Duration(hours: 16)),
      isRead: false,
      folder: EmailFolder.inbox,
    ),

    Email(
      id: 'inbox_16',
      sender: 'bob2@community.org',
      senderName: 'RPM Forum',
      recipient: ['you@example.com'],
      cc: ['admin@community.org'],
      subject: 'Another Forum Thread Reply',
      body:
          'Thanks again for your input on the topic. Your perspective continues to be helpful. This is the eighth email.',
      timestamp: DateTime.now().subtract(const Duration(days: 2)),
      isRead: true,
      folder: EmailFolder.inbox,
      category: EmailCategory.forums,
    ),
    Email(
      id: 'inbox_17',
      sender: 'social2@network.com',
      senderName: 'Facebook',
      recipient: ['you@example.com'],
      subject: 'Another Friend Request',
      body:
          'You have a new friend request from Jane Doe. This is the ninth email.',
      timestamp: DateTime.now().subtract(const Duration(hours: 6)),
      isRead: false,
      folder: EmailFolder.inbox,
      category: EmailCategory.social,
    ),
    Email(
      id: 'inbox_18',
      sender: 'support2@company.com',
      senderName: 'Support Team',
      recipient: ['you@example.com'],
      subject: 'Re: Your Support Ticket',
      body:
          'Your support ticket has been reviewed and we have a response. This is the tenth email.',
      timestamp: DateTime.now().subtract(const Duration(hours: 14)),
      isRead: false,
      folder: EmailFolder.inbox,
    ),

    Email(
      id: 'inbox_19',
      sender: 'alice3@example.com',
      senderName: 'Alice',
      recipient: ['you@example.com'],
      subject: 'Welcome back!',
      body:
          'Thanks for returning to our platform.\nWe’re always excited to have you onboard. This is the eleventh email.',
      timestamp: DateTime.now().subtract(const Duration(minutes: 40)),
      isRead: false,
      folder: EmailFolder.inbox,
      category: EmailCategory.updates,
    ),
    Email(
      id: 'inbox_20',
      sender: 'newsletter3@brand.com',
      senderName: 'BisDig',
      recipient: ['you@example.com'],
      subject: 'Even More Promotions Today',
      body:
          'Check out our latest deals on electronics, fashion, and more! This is the twelfth email.',
      timestamp: DateTime.now().subtract(const Duration(hours: 4)),
      isRead: true,
      folder: EmailFolder.inbox,
      category: EmailCategory.promotions,
    ),

    Email(
      id: 'inbox_12',
      sender: 'newsletter3@brand.com',
      senderName: 'BisDig',
      recipient: ['you@example.com'],
      subject: 'Even More Promotions Today',
      body:
          'Check out our latest deals on electronics, fashion, and more! This is the twelfth email.',
      timestamp: DateTime.now().subtract(const Duration(hours: 4)),
      isRead: true,
      folder: EmailFolder.inbox,
      category: EmailCategory.promotions,
    ),
    Email(
      id: 'inbox_13',
      sender: 'bob3@community.org',
      senderName: 'RPM Forum',
      recipient: ['you@example.com'],
      cc: ['admin@community.org'],
      subject: 'Yet Another Forum Thread Reply',
      body:
          'Thanks yet again for your input on the topic. Your perspective is invaluable. This is the thirteenth email.',
      timestamp: DateTime.now().subtract(const Duration(days: 3)),
      isRead: true,
      folder: EmailFolder.inbox,
      category: EmailCategory.forums,
    ),
    Email(
      id: 'inbox_14',
      sender: 'social3@network.com',
      senderName: 'Facebook',
      recipient: ['you@example.com'],
      subject: 'Another Another Friend Request',
      body:
          'You have a new friend request from Michael Smith. This is the fourteenth email.',
      timestamp: DateTime.now().subtract(const Duration(hours: 7)),
      isRead: false,
      folder: EmailFolder.inbox,
      category: EmailCategory.social,
    ),
    Email(
      id: 'inbox_15',
      sender: 'support3@company.com',
      senderName: 'Support Team',
      recipient: ['you@example.com'],
      subject: 'Final Response to Your Support Ticket',
      body:
          'This is the final response to your support ticket. We hope we have resolved your issue. This is the fifteenth email.',
      timestamp: DateTime.now().subtract(const Duration(hours: 16)),
      isRead: false,
      folder: EmailFolder.inbox,
    ),

    Email(
      id: 'inbox_16',
      sender: 'bob2@community.org',
      senderName: 'RPM Forum',
      recipient: ['you@example.com'],
      cc: ['admin@community.org'],
      subject: 'Another Forum Thread Reply',
      body:
          'Thanks again for your input on the topic. Your perspective continues to be helpful. This is the eighth email.',
      timestamp: DateTime.now().subtract(const Duration(days: 2)),
      isRead: true,
      folder: EmailFolder.inbox,
      category: EmailCategory.forums,
    ),
    Email(
      id: 'inbox_17',
      sender: 'social2@network.com',
      senderName: 'Facebook',
      recipient: ['you@example.com'],
      subject: 'Another Friend Request',
      body:
          'You have a new friend request from Jane Doe. This is the ninth email.',
      timestamp: DateTime.now().subtract(const Duration(hours: 6)),
      isRead: false,
      folder: EmailFolder.inbox,
      category: EmailCategory.social,
    ),

    // Starred (5)
    Email(
      id: '7',
      sender: 'important@source.com',
      senderName: 'Important Source 1',
      recipient: ['you@example.com'],
      subject: 'Important Announcement',
      body: 'This is a very important announcement.',
      timestamp: DateTime.now().subtract(const Duration(days: 4)),
      isRead: false,
      folder: EmailFolder.starred,
    ),
    Email(
      id: '8',
      sender: 'alert@service.com',
      senderName: 'Service Alert',
      recipient: ['you@example.com'],
      subject: 'Urgent: Server Downtime',
      body: 'Our servers will be down for maintenance.',
      timestamp: DateTime.now().subtract(const Duration(hours: 10)),
      isRead: true,
      folder: EmailFolder.starred,
    ),
    Email(
      id: '9',
      sender: 'boss@work.com',
      senderName: 'Boss Man',
      recipient: ['you@example.com'],
      subject: 'Meeting Tomorrow',
      body: 'Please be prepared for the meeting tomorrow at 10 AM.',
      timestamp: DateTime.now().subtract(const Duration(days: 7)),
      isRead: false,
      folder: EmailFolder.starred,
    ),
    Email(
      id: '10',
      sender: 'family@example.com',
      senderName: 'Family Member',
      recipient: ['you@example.com'],
      subject: 'Family Reunion',
      body: 'Details about the upcoming family reunion.',
      timestamp: DateTime.now().subtract(const Duration(days: 14)),
      isRead: true,
      folder: EmailFolder.starred,
    ),
    Email(
      id: '11',
      sender: 'client@company.com',
      senderName: 'VIP Client',
      recipient: ['you@example.com'],
      subject: 'Project Kickoff',
      body: 'Kickoff meeting for the new project.',
      timestamp: DateTime.now().subtract(const Duration(days: 21)),
      isRead: false,
      folder: EmailFolder.starred,
    ),

    // Snoozed (5)
    Email(
      id: '12',
      sender: 'reminder@app.com',
      senderName: 'App Reminder',
      recipient: ['you@example.com'],
      subject: 'Snoozed Reminder 1',
      body: 'This is a reminder that you snoozed.',
      timestamp: DateTime.now().subtract(const Duration(hours: 1)),
      isRead: false,
      folder: EmailFolder.snoozed,
    ),
    Email(
      id: '13',
      sender: 'postman@delivery.com',
      senderName: 'Delivery Company',
      recipient: ['you@example.com'],
      subject: 'Package Arriving',
      body: 'Your package will arrive soon.  Snoozed for later.',
      timestamp: DateTime.now().subtract(const Duration(days: 5)),
      isRead: true,
      folder: EmailFolder.snoozed,
    ),
    Email(
      id: '28',
      sender: 'doctor@clinic.com',
      senderName: 'Doctor Appointment',
      recipient: ['you@example.com'],
      subject: 'Appointment Rescheduled',
      body: 'Your appointment has been rescheduled. Snoozed.',
      timestamp: DateTime.now().subtract(const Duration(hours: 16)),
      isRead: false,
      folder: EmailFolder.snoozed,
    ),
    Email(
      id: '29',
      sender: 'course@online.com',
      senderName: 'Online Course',
      recipient: ['you@example.com'],
      subject: 'Course Deadline Approaching',
      body: 'The deadline for the course is approaching. Snoozed reminder.',
      timestamp: DateTime.now().subtract(const Duration(days: 9)),
      isRead: true,
      folder: EmailFolder.snoozed,
    ),
    Email(
      id: '30',
      sender: 'event@ticket.com',
      senderName: 'Event Tickets',
      recipient: ['you@example.com'],
      subject: 'Upcoming Event Reminder',
      body: 'Reminder about an event you have tickets for. Snoozed.',
      timestamp: DateTime.now().subtract(const Duration(days: 12)),
      isRead: false,
      folder: EmailFolder.snoozed,
    ),

    // Important (5)
    Email(
      id: '14',
      sender: 'ceo@company.com',
      senderName: 'CEO',
      recipient: ['you@example.com'],
      subject: 'Company Announcement',
      body: 'Important company-wide announcement from the CEO.',
      timestamp: DateTime.now().subtract(const Duration(days: 6)),
      isRead: true,
      folder: EmailFolder.important,
    ),
    Email(
      id: '16',
      sender: 'bank@alert.com',
      senderName: 'Bank Name',
      recipient: ['you@example.com'],
      subject: 'Fraud Alert',
      body: 'Suspicious activity detected on your account.',
      timestamp: DateTime.now().subtract(const Duration(hours: 6)),
      isRead: false,
      folder: EmailFolder.important,
    ),
    Email(
      id: '17',
      sender: 'gov@notice.com',
      senderName: 'Government',
      recipient: ['you@example.com'],
      subject: 'Tax Notice',
      body: 'Important information regarding your taxes.',
      timestamp: DateTime.now().subtract(const Duration(days: 30)),
      isRead: true,
      folder: EmailFolder.important,
    ),
    Email(
      id: '18',
      sender: 'school@update.com',
      senderName: 'School',
      recipient: ['you@example.com'],
      subject: 'School Closure',
      body: 'School will be closed due to unforeseen circumstances.',
      timestamp: DateTime.now().subtract(const Duration(days: 8)),
      isRead: false,
      folder: EmailFolder.important,
    ),
    Email(
      id: '19',
      sender: 'legal@firm.com',
      senderName: 'Law Firm',
      recipient: ['you@example.com'],
      subject: 'Legal Document',
      body: 'Important legal document requiring your attention.',
      timestamp: DateTime.now().subtract(const Duration(days: 11)),
      isRead: true,
      folder: EmailFolder.important,
    ),

    // Sent (5)
    Email(
      id: '4',
      sender: 'you@example.com',
      senderName: 'Me',
      recipient: ['friend@example.com'],
      cc: ['colleague@example.com'],
      bcc: ['manager@example.com'],
      subject: 'Project Update',
      body:
          'Hi team,\n\nHere is the latest update on the project status.\n\nRegards,\nYou',
      timestamp: DateTime.now().subtract(const Duration(days: 2)),
      isRead: true,
      folder: EmailFolder.sent,
    ),
    Email(
      id: '20',
      sender: 'you@example.com',
      senderName: 'Me',
      recipient: ['customer@email.com'],
      subject: 'Order Confirmation',
      body: 'Your order has been confirmed and will be shipped soon.',
      timestamp: DateTime.now().subtract(const Duration(days: 1)),
      isRead: true,
      folder: EmailFolder.sent,
    ),
    Email(
      id: '21',
      sender: 'you@example.com',
      senderName: 'Me',
      recipient: ['recruiter@company.com'],
      subject: 'Job Application',
      body: 'Thank you for the opportunity.  Here is my application.',
      timestamp: DateTime.now().subtract(const Duration(days: 10)),
      isRead: true,
      folder: EmailFolder.sent,
    ),
    Email(
      id: '22',
      sender: 'you@example.com',
      senderName: 'Me',
      recipient: ['vendor@company.com'],
      subject: 'Invoice Sent',
      body: 'I have attached the invoice for services rendered.',
      timestamp: DateTime.now().subtract(const Duration(days: 5)),
      isRead: true,
      folder: EmailFolder.sent,
    ),
    Email(
      id: '23',
      sender: 'you@example.com',
      senderName: 'Me',
      recipient: ['team@project.com'],
      subject: 'Project Proposal',
      body: 'Here is the project proposal for your review and feedback.',
      timestamp: DateTime.now().subtract(const Duration(days: 17)),
      isRead: true,
      folder: EmailFolder.sent,
    ),

    // Draft (5)
    Email(
      id: '6',
      sender: 'draft@draft.com',
      senderName: 'Me',
      recipient: ['draft@example.com'],
      subject: 'Unfinished Email',
      body: 'This is a saved draft, still working on it...',
      timestamp: DateTime.now().subtract(const Duration(days: 3)),
      isRead: false,
      folder: EmailFolder.draft,
    ),
    Email(
      id: '24',
      sender: 'draft@draft.com',
      senderName: 'Me',
      recipient: ['client@draft.com'],
      subject: 'Draft Proposal',
      body: 'This is a draft of a proposal.  Needs review.',
      timestamp: DateTime.now().subtract(const Duration(days: 20)),
      isRead: false,
      folder: EmailFolder.draft,
    ),
    Email(
      id: '25',
      sender: 'draft@draft.com',
      senderName: 'Me',
      recipient: ['friend@draft.com'],
      subject: 'Draft Invitation',
      body: 'This is a draft of an invitation to a party.',
      timestamp: DateTime.now().subtract(const Duration(days: 22)),
      isRead: false,
      folder: EmailFolder.draft,
    ),
    Email(
      id: '26',
      sender: 'draft@draft.com',
      senderName: 'Me',
      recipient: ['vendor@draft.com'],
      subject: 'Draft Order',
      body: 'This is a draft of an order I want to place.',
      timestamp: DateTime.now().subtract(const Duration(days: 27)),
      isRead: false,
      folder: EmailFolder.draft,
    ),
    Email(
      id: '27',
      sender: 'draft@draft.com',
      senderName: 'Me',
      recipient: ['boss@draft.com'],
      subject: 'Draft Report',
      body: 'This is a draft of the weekly report.',
      timestamp: DateTime.now().subtract(const Duration(days: 13)),
      isRead: false,
      folder: EmailFolder.draft,
    ),

    // Spam (5)
    Email(
      id: '31',
      sender: 'spam1@example.com',
      senderName: 'Spam Sender 1',
      recipient: ['you@example.com'],
      subject: 'Get Rich Quick!',
      body: 'This is a spam email promising quick riches.',
      timestamp: DateTime.now().subtract(const Duration(minutes: 5)),
      isRead: false,
      folder: EmailFolder.spam,
    ),
    Email(
      id: '32',
      sender: 'spam2@example.com',
      senderName: 'Spam Sender 2',
      recipient: ['you@example.com'],
      subject: 'You Won a Prize!',
      body: 'Congratulations! You\'ve won a valuable prize.',
      timestamp: DateTime.now().subtract(const Duration(hours: 4)),
      isRead: false,
      folder: EmailFolder.spam,
    ),
    Email(
      id: '33',
      sender: 'spam3@example.com',
      senderName: 'Spam Sender 3',
      recipient: ['you@example.com'],
      subject: 'Limited Time Offer',
      body: 'Act now to claim your limited-time offer!',
      timestamp: DateTime.now().subtract(const Duration(days: 2)),
      isRead: false,
      folder: EmailFolder.spam,
    ),
    Email(
      id: '34',
      sender: 'spam4@example.com',
      senderName: 'Spam Sender 4',
      recipient: ['you@example.com'],
      subject: 'Urgent Action Required',
      body: 'Your account will be suspended if you don\'t act now.',
      timestamp: DateTime.now().subtract(const Duration(hours: 20)),
      isRead: false,
      folder: EmailFolder.spam,
    ),
    Email(
      id: '35',
      sender: 'spam5@example.com',
      senderName: 'Spam Sender 5',
      recipient: ['you@example.com'],
      subject: 'Click Here Now!',
      body: 'Click here to claim your special reward.',
      timestamp: DateTime.now().subtract(const Duration(days: 1)),
      isRead: false,
      folder: EmailFolder.spam,
    ),

    // Trash (5)
    Email(
      id: '36',
      sender: 'trash1@example.com',
      senderName: 'Trashed Sender 1',
      recipient: ['you@example.com'],
      subject: 'Deleted Email 1',
      body: 'This email has been moved to the trash.',
      timestamp: DateTime.now().subtract(const Duration(days: 7)),
      isRead: true,
      folder: EmailFolder.trash,
    ),
    Email(
      id: '37',
      sender: 'trash2@example.com',
      senderName: 'Trashed Sender 2',
      recipient: ['you@example.com'],
      subject: 'Deleted Email 2',
      body: 'This email has been moved to the trash.',
      timestamp: DateTime.now().subtract(const Duration(days: 10)),
      isRead: true,
      folder: EmailFolder.trash,
    ),
    Email(
      id: '38',
      sender: 'trash3@example.com',
      senderName: 'Trashed Sender 3',
      recipient: ['you@example.com'],
      subject: 'Deleted Email 3',
      body: 'This email has been moved to the trash.',
      timestamp: DateTime.now().subtract(const Duration(days: 14)),
      isRead: true,
      folder: EmailFolder.trash,
    ),
    Email(
      id: '39',
      sender: 'trash4@example.com',
      senderName: 'Trashed Sender 4',
      recipient: ['you@example.com'],
      subject: 'Deleted Email 4',
      body: 'This email has been moved to the trash.',
      timestamp: DateTime.now().subtract(const Duration(days: 21)),
      isRead: true,
      folder: EmailFolder.trash,
    ),
    Email(
      id: '40',
      sender: 'trash5@example.com',
      senderName: 'Trashed Sender 5',
      recipient: ['you@example.com'],
      subject: 'Deleted Email 5',
      body: 'This email has been moved to the trash.',
      timestamp: DateTime.now().subtract(const Duration(days: 35)),
      isRead: true,
      folder: EmailFolder.trash,
    ),

    // Scheduled (3)
    Email(
      id: '37',
      sender: 'sender1@example.com', // Adjusted sender
      senderName: 'Scheduled Sender 1', // Adjusted senderName
      recipient: ['recipient1@example.com'], // Adjusted recipient
      subject: 'Scheduled Email 1',
      body: 'This is the body of the first scheduled email.', // Adjusted body
      timestamp: DateTime.now().subtract(const Duration(days: 10)),
      isRead: false, // Assuming it's a new scheduled email
      folder: EmailFolder.scheduled,
    ),
    Email(
      id: '38',
      sender: 'sender2@example.com', // Adjusted sender
      senderName: 'Scheduled Sender 2', // Adjusted senderName
      recipient: ['recipient2@example.com'], // Adjusted recipient
      subject: 'Scheduled Email 2',
      body:
          'Content for the second scheduled email goes here.', // Adjusted body
      timestamp: DateTime.now().subtract(const Duration(days: 14)),
      isRead: false, // Assuming it's a new scheduled email
      folder: EmailFolder.scheduled,
    ),
    Email(
      id: '40',
      sender: 'sender3@example.com', // Adjusted sender
      senderName: 'Scheduled Sender 3', // Adjusted senderName
      recipient: ['recipient3@example.com'], // Adjusted recipient
      subject: 'Scheduled Email 3',
      body:
          'This is the message for the third email that is scheduled.', // Adjusted body
      timestamp: DateTime.now().subtract(const Duration(days: 35)),
      isRead: false, // Assuming it's a new scheduled email
      folder: EmailFolder.scheduled,
    ),
  ];
}
